src/Domain/DonationRepository.php
* listen for valid exception types to detect locks and roll back
* try up to 5 times when acquiring a lock for a new matched donation
=> MAT-15 - lock recovery fixes

composer.lock, src/Application/Actions/Hooks/DonationUpdate.php, src/Domain/Donation.php, src/Migrations/Version20191126051351.php
This seems to currently be necessary to have tip amounts persist correctly
=> MAT-33 - remove schema-level tip default

src/Domain/FundRepository.php
Previously, campaign setup could end up never creating the approach campaign-funding link, if a Fund was created moments before by another thread
=> MAT-40 - fix race condition 

src/Application/Actions/Donations/Cancel.php
* refuse to cancel donations in finalised statuses
* skip cancelling already-cancelled donations
* add more warning and info logging as appropriate
=> MAT-47 - tighten up Cancel endpoint

.env.example, src/Domain/DonationRepository.php
And update `.env.example` with latest sandbox instance ID for new project clones
=> Log any on-demand campaign repository pull error details

app/routes.php, composer.json, composer.lock, src/Application/Auth/DonationPublicAuthMiddleware.php, src/Application/Commands/Command.php, src/Application/Commands/ExpireMatchFunds.php, src/Application/Commands/HandleOutOfSyncFunds.php, src/Application/Commands/LockingCommand.php, src/Application/Commands/PushDonations.php, src/Application/Commands/RetrospectivelyMatch.php, src/Application/Commands/UpdateCampaigns.php, tests/TestCase.php
As detailed in https://github.com/slimphp/Slim/issues/2892 there is effectively a breaking
change in v4.4 which requires this middleware's approach and tests' route handling to be updated.
=> MAT-59 - update `DonationPublicAuthMiddleware` route introspection for Slim v4.4+

Readme.md, composer.json
Includes background on the high level choices around Redis for matching etc., and enough of an overview
for new devs to dive in even if new to Slim
=> MAT-57 - expand readme with all key info

src/Application/Actions/Donations/Create.php, src/Domain/Campaign.php, src/Domain/DonationRepository.php, tests/Application/Actions/Donations/CreateTest.php
- MAT-88 start tagging stripe payment intent with useful metadata
- MAT-92 optionally set donation fields if available
=> MAT-88 + MAT-92 start tagging stripe payment intent with useful metadata

src/Client/Donation.php
- MAT-104 skip SF donation update if firstname or lastname is missing
=> MAT-104 skip SF donation update if firstname or lastname is missing

.env.example, app/routes.php, app/settings.php, src/Application/Actions/ActionPayload.php, src/Application/Actions/Hooks/StripeUpdate.php
MAT-85 stripe update webhook using Stripes own event method + update routes file
=> MAT-85 stripe update webhook

src/Application/Actions/Hooks/StripeUpdate.php
=> MAT-85 Fix status object position - stripe webhook

src/Domain/Donation.php
- MAT-108 start setting charity comm preferences when converting to hook model
=> MAT-108 charity comms webhook

src/Application/Actions/Hooks/StripeUpdate.php, tests/Application/Actions/Hooks/StripeUpdateTest.php, tests/TestData/StripeWebhook/ApiResponse/bt_invalid.json, tests/TestData/StripeWebhook/ApiResponse/bt_success.json, tests/TestData/StripeWebhook/po_paid.json
- MAT-107 start listening to payout.paid events and update donation statuses accordingly
=> MAT-107 start listening to payout.paid events and update donation statuses accordingly

src/Application/Actions/Donations/Update.php, src/Application/HttpModels/Donation.php, src/Application/HttpModels/DonationCreate.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, src/Migrations/Version20200925104750.php, tests/Application/Actions/DonationTestDataTrait.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/UpdateTest.php
- MAT-110 add new champion comms field to Donation table
- MAT-110 update http models with new champion comms field
- MAT-110 start setting champion comms flag from request data
- MAT-110 update unit tests
=> MAT-110 update donation update endpoint to handle champion comms

src/Application/Actions/Hooks/StripeUpdate.php
- MAT-113 unconditionally return payout paid response
=> MAT-113 unconditionally return payout paid response

src/Application/Actions/Hooks/StripeUpdate.php, tests/Application/Actions/Hooks/StripeUpdateTest.php, tests/TestData/StripeWebhook/ch_refunded.json
- MAT-90 add refunded event handling logic + update unit tests
- MAT-90 charge refunded event json test data
=> MAT-90 stripe refund webhook

src/Application/Actions/Donations/Create.php
MAT-115 remove special characters when building statement descriptor string
=> MAT-115 remove special characters when building statement descriptor string

src/Application/Actions/Donations/Update.php, src/Client/Donation.php, src/Domain/Donation.php, src/Migrations/Version20201113093420.php, tests/Application/Actions/DonationTestDataTrait.php, tests/Application/Actions/Donations/UpdateTest.php
And fix existing data stuck in this state.
=> MAT-118 - stop queuing donations for Salesforce push which can never succeed

src/Domain/Donation.php, src/Domain/SalesforceWriteProxyRepository.php
N.B. `getCreatedDate()` is already defined on `TimestampsTrait`.
=> MAT-131 - revert temporary logging

src/Application/Matching/OptimisticRedisAdapter.php
=> Cast method var to string

src/Application/Actions/Donations/Update.php, src/Application/HttpModels/Donation.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, src/Migrations/Version20201119104427.php, tests/Application/Actions/DonationTestDataTrait.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Domain/DonationTest.php
- MAT-111 add new charity fee field on donation table
- MAT-111 calculate and set the charity depending on psp, card brand and card country
- MAT-111 update unit tests to include latest changes
=> MAT-111 support variable fees

tests/Application/Actions/Hooks/DonationUpdateTest.php
- Add enthuse ga fee calculation postive and negative unit tests
=> MAT-133 Add enthuse ga fee calculation unit test

src/Application/Actions/Donations/Update.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Actions/Hooks/DonationUpdateTest.php
=> Develop -> master

src/Application/Actions/Hooks/StripePayoutUpdate.php, tests/Application/Actions/Hooks/StripePayoutUpdateTest.php
=> MAT-124 update method call

src/Application/Actions/Hooks/StripeChargeUpdate.php
- Handle refunds on donations from other sandboxes gracefully
=> Handle refunds on donations from other sandboxes gracefully

composer.json, src/Domain/Donation.php, src/Migrations/Version20201208101014.php
* truncate first names at 40 characters when building API bodies – Should fix SF pushes in the case where a longer name has been saved
* apply data fixes
=> MAT-147 - name data fixes

src/Application/Messenger/Handler/StripePayoutHandler.php
=> MAT-160 - avoid error logging when refunds appear on payout txn lists

src/Domain/Campaign.php
Hopefully fix mysterious campaign update task crash
=> MAT-166 - make currency code type nullable for now

app/settings.php, src/Application/Fees/Calculator.php, src/Domain/DonationRepository.php, tests/Application/Actions/Hooks/StripeChargeUpdateTest.php, tests/Application/Fees/CalculatorTest.php, tests/Domain/DonationRepositoryTest.php, tests/TestData/StripeWebhook/ApiResponse/bt_success_sek.json, tests/TestData/StripeWebhook/ch_succeeded_sek.json
=> MAT-165 - support fixed fee amounts in other currencies

composer.json
Including migrations table, instead of reversing migrations individually
=> MAT-174 - Drop full DB

composer.lock, src/Application/Messenger/Handler/StripePayoutHandler.php, tests/Application/Messenger/Handler/StripePayoutHandlerTest.php
* fix `starting_after` callout typo
* add proper error logging on balance txn callout errors
* improve logging verbosity in the rest of `StripePayoutHandler`
=> MAT-181 – fix big payout callouts

src/Application/Fees/Calculator.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, tests/Application/Fees/CalculatorTest.php, tests/Application/VatTrait.php, tests/Domain/DonationRepositoryTest.php
Also BG2-1871 – fix unit test so we are actually checking the VAT scenarios
diverge as expected
=> MAT-179 - fix fee cover transfer amounts

src/Domain/Donation.php, src/Migrations/Version20210907103000.php
Doing this in a separate step ahead of logic changes so deploys can roll out safely
=> MAT-179 - add fee cover field

src/Client/Donation.php
While the specific new failure mode's handling is not covered by a new unit
test, the exception it throws and the sandbox handling of that are both
identical to the campaign 404 case we already implemented to reduce noise
after sandbox refreshes.
=> MAT-194 - skip donations with a newly-observed kind of sandbox data push error

src/Application/Commands/ClaimGiftAid.php, tests/Application/Commands/ClaimGiftAidTest.php, tests/Application/DonationTestDataTrait.php, tests/Application/Messenger/Handler/GiftAidErrorHandlerTest.php, tests/Domain/DonationRepositoryTest.php, tests/Domain/DonationTest.php
Test:
* Gift Aid claim command;
* Gift Aid incoming error message handler;
* Fee derivation at donation repo level;
* Donation model conversion to ClaimBot message structure.
=> MAT-193 - Gift Aid integration unit tests

src/Application/Actions/Donations/Update.php, src/Domain/Donation.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Domain/DonationTest.php
Also tweak existing donation amount validation messages to
work in non-GBP currencies.
=> MAT-203 - handle invalid tip amount in Updates better too

src/Application/Actions/Donations/Create.php
This reverts commit 1561e7f1787b1cb414b35497d0d5258467994902.
=> MAT-205 – Revert "MAT-204 - try to break suspected accidental Create loop"

src/Application/Actions/Donations/Create.php
Reverts thebiggive/matchbot#281
Re-implements the block made on MAT-204. We're seeing a flood come in again!
=> MAT-208 Revert "MAT-205 – Revert "MAT-204 - try to break suspected accidental Create loop""

composer.json, matchbot-cli.php, src/Application/Commands/ClaimGiftAid.php, tests/Application/Actions/Hooks/StripePayoutUpdateTest.php, tests/Application/Commands/ClaimGiftAidTest.php, tests/TestData/StripeWebhook/po_created.json
Also resolve a Stripe hook unit test notice
=> CLA-6 – fixes for Gift Aid claim logic

src/Domain/CampaignRepository.php
Even if charities opt out of TBG claims for new donations
=> MAT-225 - keep storing HMRC reference number when available

src/Application/Commands/HandleMissedPayouts.php, src/Domain/DonationRepository.php
* Query for impacted accounts much more efficiently
* Iterate on payouts response data correctly
=> MAT-226 – fix data fix logic

src/Application/Actions/Hooks/StripeChargeUpdate.php, src/Application/HttpModels/Donation.php, src/Domain/Donation.php, tests/Application/Actions/Hooks/StripeChargeUpdateTest.php, tests/Application/DonationTestDataTrait.php
Reverts thebiggive/matchbot#334
=> Revert "BG2-1946 added support for refunded tip amount"

src/Migrations/Version20220318111320.php
Where orgs have told us they will claim it themselves
=> BG2-2014 – un-mark CC21 donations for TBG Gift Aid claiming

src/Domain/DonationRepository.php, tests/Domain/DonationRepositoryTest.php
While we investigate odd HMRC behaviour
=> CLA-18 – temporarily cap at 1k donations per run

src/Domain/Donation.php
Also trim inputs more proactively as we've seen leading
space throw off the initial pattern match
=> CLA-21 – truncate all long house no's

app/settings.php, src/Application/Handlers/ShutdownHandler.php
And increase minimum log level to INFO outside of local dev env
=> INFRA-58 – ensure deprecations don't make the whole request bail out

composer.json, src/Migrations/Version20220421121601.php
@alihejazi  see also https://github.com/thebiggive/infrastructure/commit/4b9d6b3b92ac4686fdcdf10e6d2e61cee1fac18c re the minor queue timing tweak
=> CLA-25 – reset donations caught up in regulator data blip today

src/Application/Actions/Hooks/StripeChargeUpdate.php
Most notably, ensure that we have the donation UUID in logs from charge.succeeded Stripe webhook logs,
for quick comparison to other app events impacting the same donation.
=> MAT-244 – expand and rationalise logs

app/dependencies.php, src/Application/Actions/Hooks/StripeChargeUpdate.php, src/Domain/Donation.php, tests/Application/DonationTestDataTrait.php, tests/Domain/DonationTest.php
Reverts thebiggive/matchbot#389
We need the new Salesforce code out too before the model can send `collectedTime` safely.
=> Revert "Develop -> main"

.env.example, app/dependencies.php, app/routes.php, app/settings.php, composer.json, composer.lock, phpunit.xml, src/Application/Actions/Donations/Create.php, src/Application/Auth/DonationPublicAuthMiddleware.php, src/Application/Auth/DonationToken.php, src/Application/Auth/IdentityToken.php, src/Application/Auth/PersonManagementAuthMiddleware.php, src/Application/HttpModels/DonationCreate.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, src/Migrations/Version20220917172013.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/GetTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Auth/DonationRecaptchaMiddlewareTest.php, tests/Application/Auth/DonationTokenTest.php, tests/Application/Auth/IdentityTokenTest.php, tests/Application/Auth/PersonManagementAuthMiddlewareTest.php, tests/Application/Auth/TokenTest.php, tests/Application/Commands/UpdateCampaignsTest.php, tests/TestCase.php
=> MAT-109 – supporting setting existing Stripe Customer ID

src/Application/Actions/Donations/Create.php, src/Application/Actions/Donations/Update.php, src/Application/Fees/Calculator.php, src/Application/HttpModels/Donation.php, src/Application/HttpModels/DonationCreate.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, src/Migrations/Version20221025044553.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Domain/DonationRepositoryTest.php, tests/Domain/DonationTest.php
Including "card" for existing behaviour and newly-supported "customer_balance".
=> MAT-266, MAT-267 – support variable payment methods

src/Migrations/Version20221021174752.php
It's already paid out so can skip Collected.
=> MAT-260 – fix donation's status

.circleci/config.yml, composer.json, composer.lock, psalm-baseline.xml, psalm.xml, src/Application/Actions/ActionError.php, src/Application/Persistence/RetrySafeEntityManager.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/GetTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Commands/AlwaysAvailableLockStore.php, tests/Application/Commands/HandleOutOfSyncFundsTest.php, tests/Application/Commands/RetrospectivelyMatchTest.php, tests/Application/Persistence/RetrySafeEntityManagerTest.php, tests/Domain/DonationRepositoryTest.php, tests/Domain/FundRepositoryTest.php
=> MAT-284: Install Psalm

composer.json, composer.lock, psalm-baseline.xml, psalm.xml
Enabled config options findUnusedBaselineEntry and findUnusedCode that will be on by default in Psalm 6
=> Update Psalm to 5.7.4

integrationTests/bootstrap.php
No reason these should ever happen, but worth having this just in case we tried to run by accident
=> Block integration test run in prod

app/routes.php, src/Application/Actions/UpdatePaymentMethod.php, tests/Application/Actions/UpdatePaymentMethodTest.php
Based on a copy of the DeletePaymentMethod controller
=> ID-38: Add UpdatePaymentMethod controller

app/routes.php
Reduce redundant config where a common path has a common set of middlewares
=> Give `payment_methods` a routing group

.circleci/config.yml
In hopes of fixing uploads of coverage reports, which stopped completing a couple of weeks ago
=> Upgrade codecov orb

app/dependencies.php, composer.json, psalm-baseline.xml, src/Application/Actions/Hooks/StripeChargeUpdate.php, src/Application/Actions/Hooks/StripePayoutUpdate.php, src/Application/Notifier/StripeChatterInterface.php, tests/Application/Actions/Hooks/StripeChargeUpdateTest.php, tests/Application/Actions/Hooks/StripePayoutUpdateTest.php, tests/TestCase.php, tests/TestData/StripeWebhook/ch_dispute_closed_lost_higher_amount.json, tests/TestData/StripeWebhook/ch_over_refunded.json, tests/TestData/StripeWebhook/ch_refunded_but_original_failed.json
And tidy up our #stripe Slack notification config a bit
=> MAT-293 – support over-refunds

integrationTests/CreateDonationTest.php, integrationTests/IntegrationTest.php, integrationTests/bootstrap.php, src/Application/HttpModels/DonationCreate.php
=> MAT-301: Refactor, make all props of DonationCreate constructor args + add integration test for creating donation

src/Application/Commands/DeleteStalePaymentDetails.php, tests/Application/Commands/DeleteStalePaymentDetailsTest.php
Maybe we can do more at once if it doesn't take long to run
=> MAT-295: Log time taken to delete each batch of stale payment details

src/Domain/Donation.php, tests/Domain/DonationTest.php
And tidy up comparison operator + types
Effectively post-merge review suggestions from a quick skim of https://github.com/thebiggive/matchbot/pull/560/files
=> DON-772 – Fix checking for customer balance tips under £1

src/Migrations/Version20230707100241.php
Following processing errors with the first claim attempt
=> MAT-303 – mark one campaign for a new Gift Aid claim

src/Application/Actions/Donations/Create.php, src/Domain/Donation.php, tests/Application/Actions/Donations/CreateTest.php, tests/Domain/DonationTest.php
Adjustments to matchbot prep for new Stripe Payment element as discussed with @NoelLH .
=> Don 855 ii

src/Application/Actions/Donations/Confirm.php
=> Catch exception and stop alarming us when payment methods fail

integrationTests/DonationRepositoryTest.php, src/Application/Commands/ExpireMatchFunds.php, src/Domain/DonationRepository.php, tests/Application/Commands/ExpireMatchFundsTest.php
=> MAT-324: Expire match funding for cancelled donations as well as pending donations 32 mins after creation

matchbot-cli.php, psalm-baseline.xml, psalm.xml
Not sure how Psalm didn't stop this breakage getting to staging though.
=> MAT-306: Fix breakage that was never in prod.

.circleci/config.yml, integrationTests/CreateDonationEvenWhenEntityManagerClosesAfterFirstPersistsTest.php, src/Domain/DonorAccount.php
This was part of the much bigger PR #645 where I was trying to stop letting Doctrine manage the association between Donation and Campaign - but that's several kinds of broken. So I've just salvaged the first three commits from it here.
=> Mat 322 fix annotation

psalm-baseline.xml, src/Domain/CampaignFundingRepository.php, src/Domain/DonationRepository.php
Mostly 2019 vintage things from before we went with Redis for all very-realtime matching operations
=> Tidy up stray lock helpers & comments

src/Application/Actions/Donations/Confirm.php, src/Application/Actions/Donations/Create.php, src/Application/Actions/Donations/Update.php, src/Application/PSPStubber.php
Just trying to cover scenarios that would be exercised by load tests for now. And obviously this is not trying to follow normal coding styles, trying to get something usable rapidly instead.
=> CC-90: Stub out real stripe for load test purposes

src/Application/PSPStubber.php
=> Only bypass stripe if BYPASS_PSP is 'true' (not 'false')

.gitignore, Readme.md, docker-compose.yml, stripe_cli.env.example
…ng display of thanks page
Needs some more work, at the very least adding documentation.
=> MAT-315: Using Stripe CLI, allow connecting local dev environments to real stripe webhooks

psalm-baseline.xml, tests/Domain/DonationTest.php
Before: https://output.circle-artifacts.com/output/job/7450cbaa-974a-47f0-ba6e-77c3f934e836/artifacts/0/reports/infection.html#mutant/Domain/Donation.php
After (although if this isn't reviewed straight away I might push some more tests into the same branch):
https://output.circle-artifacts.com/output/job/900bc9e3-22f8-4d18-b2c3-c3eb2a07e0bd/artifacts/0/reports/infection.html#mutant/Domain/Donation.php
=> MAT-326: Add some donation model unit tests

src/Domain/Donation.php, tests/Application/DonationTestDataTrait.php, tests/Domain/DonationTest.php
MSI for this file increased from 70.6 to 71.43, 4 additional mutants killed.
Before: https://output.circle-artifacts.com/output/job/1c65e43c-aefa-4a7c-bafe-610ca6edd0c1/artifacts/0/reports/infection.html#mutant/Domain/Donation.php
After: https://output.circle-artifacts.com/output/job/27c3a95e-0b4d-46f5-b543-7247babe5fe6/artifacts/0/reports/infection.html#mutant/Domain/Donation.php
Edit - pushed some more commits that should kill at least 2 more mutants.
=> Mat 326: Add more tests for Donation model

tests/Domain/FundRepositoryTest.php
Before:  https://output.circle-artifacts.com/output/job/4b7de647-6b12-4d54-a7ea-c80733ef0ef0/artifacts/0/reports/infection.html#mutant/Domain/FundRepository.php
After: https://output.circle-artifacts.com/output/job/a6e281e8-7f3c-4c6a-bf37-2f48a55106fc/artifacts/0/reports/infection.html#mutant/Domain/FundRepository.php
=> MAT-326: Add more test assertions for FundRepository

src/Application/Actions/Donations/Confirm.php, src/Client/LiveStripeClient.php, src/Client/Stripe.php, src/Client/StubStripeClient.php, tests/Application/Actions/Donations/ConfirmTest.php
Reverts thebiggive/matchbot#710
=> Revert "MAT-340 – add detail to a Stripe Payment Method before confirming it"

app/dependencies.php, app/repositories.php, composer.json, composer.lock, integrationTests/DonationMatchingTest.php, integrationTests/IntegrationTest.php, psalm-baseline.xml, psalm.xml, src/Domain/DonationRepository.php
Simplifies our code and enhances the ability of Psalm to catch errors.
=> Use psalm plugin psr container

matchbot-cli.php, public/index.php, src/Application/Security/CorsMiddleware.php, src/Domain/CampaignFundingRepository.php
=> Cors class typo fix

composer.json, src/Application/Commands/HandleOutOfSyncFunds.php, tests/Application/Commands/HandleOutOfSyncFundsTest.php
Reverts thebiggive/matchbot#719
=> Revert "Prepare a one-off patch command mode for CampaignFunding ID 27190"

src/Application/Actions/Donations/Confirm.php, src/Client/LiveStripeClient.php, src/Client/Stripe.php, src/Client/StubStripeClient.php, src/Domain/Donation.php, tests/Application/Actions/Donations/ConfirmTest.php, tests/Domain/DonationTest.php
With more edge case considerations than #710
=> MAT-340 – add detail to a Stripe Payment Method before confirming it

src/Application/Actions/Donations/Update.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/DonationTestDataTrait.php
i.e. donation fund top-up pseudo-tips
=> MAT-335 – test amended special behaviour for Big Give general donations

src/Migrations/Version20240102160835.php
=> MAT-351 – re-queue one campaigns' donations for Gift Aid claiming

src/Application/Commands/DeleteStalePaymentDetails.php
Recently triggered an alarm to staging-alarms channel
=> BG2-2548: Don't attempt to run change to stripe rep outside production

src/Migrations/Version20240304100904.php, src/Migrations/Version20240304105340.php
=> CLA-37: Avoid possible duplicate GA claim + mark donations as paid / ready to claim

composer.json, composer.lock
infection/infection (0.27.9 => 0.27.11)
phpspec/prophecy-phpunit (v2.1.0 => v2.2.0)
phpunit/phpunit (9.6.15 => 9.6.17)
psalm/plugin-phpunit (0.18.4 => 0.19.0)
vimeo/psalm (5.22.0 => 5.23.1)
=> Update dev dependancies

src/Application/Actions/UpdatePaymentMethod.php
Same as other declines, bad CVC etc.
=> More quietly log card update attempts when cards have expired

src/Application/Matching/Adapter.php, tests/Application/Matching/AdapterTest.php, tests/Application/Matching/ArrayMatchingStorage.php, tests/Domain/DonationRepositoryMatchFundsAllocationTest.php
See also spike commit accidentally pushed to develop (and then reverted):  https://github.com/thebiggive/matchbot/commit/af89e236e3e12e456186bb5d53d56da045a7ffc8
=> Mat 332 real time storage understanding

src/Domain/Donation.php, tests/Domain/DonationTest.php
=> WIP: Log + return which disallowed amount was requested on donation init

.circleci/config.yml, integrationTests/DonationRepositoryTest.php, src/Domain/Fund.php, src/Domain/FundRepository.php, src/Migrations/Version20240502173659.php, tests/Application/Commands/RedistibuteMatchFundsTest.php, tests/Application/Commands/ResetMatchingTest.php, tests/Domain/FundRepositoryTest.php
There were no calls to Fund::getAmount except in test classes, showing that Matchbot was not using this data.
=> Mat 361 bg2 2621 remove fund amount

src/Migrations/Version20240521122101.php
(see slack thread in #gift-aid from May 2nd)
=> Remove GA for non-elgible donations

.psalm/psalm-baseline.xml, src/Application/Matching/Adapter.php, src/Application/Messenger/Handler/StripePayoutHandler.php, src/Domain/CampaignRepository.php, src/Domain/DonationRepository.php, src/Domain/FundRepository.php, src/Domain/SalesforceProxyRepository.php, src/Domain/SalesforceReadProxyRepository.php, src/Domain/SalesforceWriteProxyRepository.php, tests/Application/Commands/HandleOutOfSyncFundsTest.php
As well as fixing the issues Psalm considers most server, this increases our type coverage from 98.8430% to 98.9690%.
=> Type fixes

src/Application/Fees/Calculator.php
=> Clarify fee logic and docs

app/dependencies.php, consume-messages.sh, docker-compose.yml, integrationTests/RedistributeMatchingCommandTest.php, matchbot-cli.php, phpunit-integration.xml, src/Application/Actions/Donations/Confirm.php, src/Application/Actions/Donations/Create.php, src/Application/Actions/Donations/Update.php, src/Application/Actions/Hooks/StripePaymentsUpdate.php, src/Application/Commands/RedistributeMatchFunds.php, src/Application/Commands/RetrospectivelyMatch.php, src/Application/Messenger/DonationStateUpdated.php, src/Application/Messenger/Handler/DonationStateUpdatedHandler.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Domain/SalesforceWriteProxyRepository.php, tests/Application/Actions/Donations/ConfirmTest.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/UpdateHandlesLockExceptionTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Actions/Hooks/StripePaymentsUpdateTest.php, tests/Application/Commands/RedistributeMatchFundsTest.php, tests/Application/Commands/RetrospectivelyMatchTest.php, tests/Application/Messenger/Handler/DonationStateUpdatedHandlerTest.php, tests/Domain/DonationTest.php, tests/TestCase.php
Reverts thebiggive/matchbot#885
Looks like alarm in regtest was a transient issue.
=> Revert "Revert "Mat 363 skip retry safe""

app/dependencies.php, consume-messages.sh, docker-compose.yml, integrationTests/RedistributeMatchingCommandTest.php, matchbot-cli.php, phpunit-integration.xml, src/Application/Actions/Donations/Confirm.php, src/Application/Actions/Donations/Create.php, src/Application/Actions/Donations/Update.php, src/Application/Actions/Hooks/StripePaymentsUpdate.php, src/Application/Commands/RedistributeMatchFunds.php, src/Application/Commands/RetrospectivelyMatch.php, src/Application/Messenger/DonationStateUpdated.php, src/Application/Messenger/Handler/DonationStateUpdatedHandler.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Domain/SalesforceWriteProxyRepository.php, tests/Application/Actions/Donations/ConfirmTest.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/UpdateHandlesLockExceptionTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Actions/Hooks/StripePaymentsUpdateTest.php, tests/Application/Commands/RedistributeMatchFundsTest.php, tests/Application/Commands/RetrospectivelyMatchTest.php, tests/Application/Messenger/Handler/DonationStateUpdatedHandlerTest.php, tests/Domain/DonationTest.php, tests/TestCase.php
https://github.com/thebiggive/matchbot/pull/866 plus a log for where we think it sometimes crashes
=> MAT-363 – re-apply and log more

app/dependencies.php, consume-messages.sh, docker-compose.yml, integrationTests/RedistributeMatchingCommandTest.php, matchbot-cli.php, phpunit-integration.xml, src/Application/Actions/Donations/Confirm.php, src/Application/Actions/Donations/Create.php, src/Application/Actions/Donations/Update.php, src/Application/Actions/Hooks/StripePaymentsUpdate.php, src/Application/Commands/RedistributeMatchFunds.php, src/Application/Commands/RetrospectivelyMatch.php, src/Application/Messenger/DonationStateUpdated.php, src/Application/Messenger/Handler/DonationStateUpdatedHandler.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Domain/SalesforceWriteProxy.php, src/Domain/SalesforceWriteProxyRepository.php, tests/Application/Actions/Donations/ConfirmTest.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/UpdateHandlesLockExceptionTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Actions/Hooks/StripePaymentsUpdateTest.php, tests/Application/Commands/RedistributeMatchFundsTest.php, tests/Application/Commands/RetrospectivelyMatchTest.php, tests/Application/Messenger/Handler/DonationStateUpdatedHandlerTest.php, tests/Domain/DonationRepositoryTest.php, tests/Domain/DonationTest.php, tests/TestCase.php
Reverts thebiggive/matchbot#909
=> Re-apply new message queue based SF-push method

src/Application/Messenger/Handler/DonationStateUpdatedHandler.php, src/Domain/DonationRepository.php, tests/Application/Messenger/Handler/DonationStateUpdatedHandlerTest.php
Reverts thebiggive/matchbot#919
=> Revert "MAT-363 – find donations in advance of push in a briefly-locking transaction"

.psalm/psalm-baseline.xml, Readme.md, app/dependencies.php, composer.json, composer.lock, integrationTests/IntegrationTest.php, src/Application/Actions/Donations/Create.php, src/Application/Actions/Hooks/Stripe.php, src/Application/Persistence/RetrySafeEntityManager.php, src/Client/Common.php, src/Domain/DonationService.php, src/Domain/SalesforceWriteProxy.php, tests/Domain/DonationServiceTest.php, tests/TestCase.php
See Symfony Rate Limiter docs here: https://symfony.com/doc/current/rate_limiter.html . They do somewhat assume you're using Symfony framework though.
I'm planning to make a PR to frontend display a spinner if the rate limit is hit, but I think this is fine without it - you'll just get our generic something went wrong / please try again message when trying to move on from the first step in the stepper if you've exhausted the rate limit.
=> Mat 364 card testing prevention

.env.example, app/routes.php, composer.json, integrationTests/PullCharityUpdatedBasedOnSfHookTest.php, matchbot-cli.php, phpunit-integration.xml, phpunit.xml, src/Application/Actions/Charities/UpdateCharityFromSalesforce.php, src/Application/Commands/UpdateCharities.php, src/Domain/CampaignRepository.php, src/Domain/Charity.php, src/Domain/CharityRepository.php, src/Migrations/Version20240712140753.php, tests/TestCase.php
I think this should complete the work in matchbot for this ticket. Work still required in Salesforce and infrastructure.
=> BG2-2620: Add command for updating charities from SF when required

.psalm/psalm-baseline.xml, app/dependencies.php, app/routes.php, src/Application/Auth/PersonManagementAuthMiddleware.php, src/Application/Commands/UpdateCampaigns.php, src/Application/HttpModels/Donation.php, src/Application/HttpModels/DonationCreatedResponse.php, src/Application/Matching/Adapter.php, src/Application/Matching/LessThanRequestedAllocatedException.php, src/Application/Messenger/Handler/StripePayoutHandler.php, src/Client/Donation.php, src/Domain/CampaignFunding.php, src/Domain/CampaignRepository.php, src/Domain/CommandLockKeys.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Domain/FundRepository.php, src/Domain/FundingWithdrawal.php, src/Domain/SalesforceReadProxy.php, tests/Application/Actions/Hooks/StripePaymentsUpdateTest.php, tests/Application/Actions/StatusTest.php, tests/Application/Auth/PersonManagementAuthMiddlewareTest.php, tests/Application/Auth/PersonWithPasswordAuthMiddlewareTest.php, tests/Application/Commands/UpdateCampaignsTest.php, tests/Domain/FundRepositoryTest.php, tests/TestCase.php
Just to make the code marginly easier to work with. Reduces count of Psalm errors from 537 to 467, a 13% reduction.
=> Fix Psalm issues from baseline

app/routes.php, integrationTests/ListRegularGivingMandatesTest.php, src/Application/Actions/RegularGivingMandate/GetAllForUser.php, src/Application/Auth/IdentityToken.php, src/Application/Auth/PersonManagementAuthMiddleware.php, src/Application/Environment.php, src/Domain/Currency.php, src/Domain/Money.php, src/Domain/PersonId.php, src/Domain/Salesforce18Id.php
The main thing here is the start of working out what a regular giving mandate looks like as a JSON model to be served to front end for the donor to view. I'm sure we'll refine it as we go but worth spending time working out what we think we'll need now. Probably easiest to view and discuss it in the test file `ListRegularGivingMandatesTest.php`.
For now the data is all hard coded dummy data. Once we've decided what we want it to look like I'll go ahead and implement the mandate as an entity to load with Doctrine.
=> DON-1025: Add stubbed out RegularGiving/GetAllForUser route

integrationTests/ListRegularGivingMandatesTest.php, src/Domain/RegularGivingMandate.php, tests/Domain/RegularGivingMandateTest.php
Currently thinking we won't ask for regular tips
=> DON-1025: Remove tip from regular giving mandate

src/Domain/Charity.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Domain/MandateService.php, src/Domain/RegularGivingMandate.php
… donation"
This reverts commit e8d8c6513e9a50d64d23a7ffe1fbbad97f4505e6.
Didn't work because the createdAt value is overwitten by the ORM\PrePersist callback
=> MAT-376: Do not allocate match funds for auto donations etc

src/Application/Actions/Donations/Confirm.php, src/Client/LiveStripeClient.php, src/Client/Stripe.php, src/Client/StubStripeClient.php, src/Domain/DonationService.php, src/Domain/StripeConfirmationTokenId.php, tests/Application/Actions/Donations/ConfirmTest.php
Everything else tagged with the issue on `develop` now LGTM
=> DON-896 – review tweaks

src/Application/Actions/Charities/UpdateCharityFromSalesforce.php, src/Application/Messenger/Handler/CharityUpdatedHandler.php
=> Revert "BG2-2722 – log more when updating a charity from Salesforce"

.psalm/psalm-baseline.xml, app/dependencies.php, app/routes.php, src/Application/Actions/Donations/Confirm.php, src/Application/Security/CorsMiddleware.php
Drop previous env var support for doing so
=> INFRA-132 – stub out Stripe (bypass PSP) only with HTTP header `X-Is-Load-Test`

src/Domain/CampaignFunding.php, src/Domain/Charity.php, tests/Domain/CampaignFundingTest.php, tests/Domain/CharityTest.php, tests/TestCase.php
=> Add test coverage

api.yaml, app/routes.php, src/Domain/RegularGivingMandate.php
Also proposes to start migrating `DonorAccount\Create` to an endpoint more consistent with others (supporting both for now).
=> Update API contract

src/Migrations/Version20241016110231.php
MatchBot fields are all correct already.
=> MAT-377 – patch one donation to cause a Salesforce re-push

app/routes.php
For after next Donate Production deploy
=> Remove the old route to `DonorAccount\Create`

integrationTests/CreateRegularGivingMandateTest.php, src/Application/Actions/RegularGivingMandate/Create.php, src/Domain/DonorAccount.php, src/Domain/MandateService.php, tests/TestData/Identity.php
=> DON-998: Create first donation with regular giving mandate

src/Application/Messenger/Handler/StripePayoutHandler.php
Reverts thebiggive/matchbot#1070
=> Revert "Make no-charge payouts only an `INFO` log until Monday's adjustments are finalised"

src/Migrations/Version20241129163132.php
Salesforce Account ID 0011r00002Hof4XAAR
=> Remove Gift Aid info for a now-inactive charity following an organisational merge

integrationTests/RedistributeMatchingCommandTest.php, matchbot-cli.php, src/Application/Commands/RedistributeMatchFunds.php, src/Application/Matching/Adapter.php, src/Application/Matching/MatchFundsRedistributor.php, src/Domain/CampaignFundingRepository.php, src/Domain/DonationRepository.php, tests/Application/Commands/RedistributeMatchFundsTest.php, tests/Domain/DonationRepositoryMatchFundsAllocationTest.php
(except semi-related minor refactoring)
=> MAT-393 – revert everything used for temporary data patch which is done now

app/dependencies.php, integrationTests/CreateRegularGivingMandateTest.php, integrationTests/DonationMatchingTest.php, integrationTests/IntegrationTest.php, src/Domain/RegularGivingMandate.php, src/Domain/RegularGivingNotifier.php, src/Domain/RegularGivingService.php, tests/Domain/RegularGivingNotifierTest.php, tests/Domain/RegularGivingServiceTest.php
WIP but should be fine to merge given that we know we need to address todo before launching the service or marking ticket done.
=> DON-1009: WIP send emails for new regular giving mandates

app/dependencies.php, matchbot-cli.php
My local now gets as far as trying to read messages (and crashing because my local queue has the old stamp path). I think that's probably enough to be semi-confident that it will fix the real queues.
=> Fix Messenger consumer command DI

src/Domain/DonorAccount.php, tests/Domain/RegularGivingMandateTest.php
See https://github.com/thebiggive/salesforce/pull/2183#discussion_r1925121006
=> BG2-2797: SF API change, rename ID field in mandate donor

src/Domain/FundRepository.php
=> DON-999 – error log if a known fund's value decreases

src/Application/Actions/RegularGivingMandate/Create.php, src/Application/HttpModels/MandateCreate.php, src/Domain/DomainException/HomeAddressRequired.php, src/Domain/DonorAccount.php, src/Domain/RegularGivingMandate.php, src/Domain/RegularGivingService.php, tests/Application/HttpModels/MandateCreateTest.php, tests/Domain/RegularGivingServiceTest.php
=> DON-1008: Allow claiming gift aid with regular giving donations

src/Application/Commands/SetupTestMandate.php, src/Application/HttpModels/MandateCreate.php, src/Domain/DonorAccount.php, src/Domain/PostCode.php, src/Domain/RegularGivingService.php, tests/Domain/PostcodeTest.php, tests/Domain/RegularGivingMandateTest.php, tests/Domain/RegularGivingServiceTest.php
We will want to add similar validation to front end.
=> DON-1008: Add validation for home postcode as used for GA on regular giving

src/Application/Actions/Donations/Update.php, src/Application/Actions/Hooks/StripePaymentsUpdate.php, src/Application/Matching/MatchFundsRedistributor.php, src/Domain/Currency.php, src/Domain/DoctrineDonationRepository.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Domain/Money.php, src/Domain/RegularGivingMandate.php, src/Domain/RegularGivingNotifier.php, tests/Domain/DonationRepositoryTest.php
Trying to avoid hard-coding currency in more places than we have to.
=> DON-1003: Remove some hard-coded GBP currencies

src/Domain/DoctrineDonationRepository.php
This was never tested until now that I've built the frontend part.
=> DON-1022: Fix DQL broken used in regular giving mandate cancellation

.psalm/psalm-baseline.xml, tests/Application/Fees/WebsiteExamplesCalculatorTest.php
I think I might have run into a Psalm bug where I couldn't suppress all the issues I wanted to, so one issue is added to baseline.
=> OPS-735: Add website fee worked examples as unit tests

composer.json, composer.lock, dbal-funcational-index.patch.txt, integrationTests/ListRegularGivingMandatesTest.php, src/Application/Actions/RegularGivingMandate/Create.php, src/Domain/DomainException/MandateAlreadyExists.php, src/Domain/MandateCancellationType.php, src/Domain/RegularGivingMandateRepository.php, src/Domain/RegularGivingService.php, src/Migrations/Version20250228124233.php
=> DON-1005: Disallow donor from having two active or pending mandates for one campaign

integrationTests/CampaignRepositoryTest.php, src/Application/Commands/UpdateCampaigns.php, src/Domain/CampaignRepository.php, tests/Application/Commands/UpdateCampaignsTest.php
… findCampaignsThatNeedToBeUpToDate
=> DON-995: Keep all regular giving campaign info up to date from salesforce

src/Domain/DonationNotifier.php
person UUID is a string not a number
=> ID-47: Fix donor account signup link

composer.json, matchbot-cli.php, src/Application/Commands/PushDailyFundTotals.php, src/Application/Commands/RetrospectivelyMatch.php, src/Domain/FundRepository.php
Expected to be scheduled daily
=> MAT-415 – add current campaigns fund totals push to Salesforce

integrationTests/PushDailyFundTotalsTest.php, src/Domain/FundRepository.php, tests/Domain/PostcodeTest.php
~~Failing but maybe intermittently?~~
(fixed)
From my local:
```
There was 1 error:
1) MatchBot\IntegrationTests\PushDailyFundTotalsTest::testRun
MatchBot\Application\AssertionFailedException: Provided "-25000" is neither greater than or equal to "0" nor less than or equal to "2000000000".
/var/www/html/vendor/beberlei/assert/lib/Assert/Assertion.php:2728
/var/www/html/vendor/beberlei/assert/lib/Assert/Assertion.php:2330
/var/www/html/src/Domain/Money.php:26
/var/www/html/src/Domain/Money.php:160
/var/www/html/src/Domain/Fund.php:129
/var/www/html/src/Domain/Fund.php:156
/var/www/html/src/Application/Messenger/FundTotalUpdated.php:22
...
```
=> MAT-415 add integration test `PushDailyFundTotalsTest`

.circleci/config.yml
See https://github.com/thebiggive/identity/pull/222
=> Don't notify slack or Jira for issues in ephemeral branches

integrationTests/CallFrequentCommandsTest.php
Should stop failures like below that I've been seeing on-and-off on my local for months:
```diff
.............F...................                                 33 / 33 (100%)
Time: 00:05.514, Memory: 32.00 MB
There was 1 failure:
1) MatchBot\IntegrationTests\CallFrequentCommandsTest::testTick
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
Sent 2 metrics to CloudWatch
matchbot:send-statistics complete!
matchbot:expire-match-funds starting!
-Released 0 donations' matching
+Released 1 donations' matching
matchbot:expire-match-funds complete!
matchbot:expire-pending-mandates starting!
matchbot:expire-pending-mandates complete!
/var/www/html/integrationTests/CallFrequentCommandsTest.php:52
FAILURES!
Tests: 33, Assertions: 300, Failures: 1.
```
=> Fix local flaking of \MatchBot\IntegrationTests\CallFrequentCommandsTest

composer.json, composer.lock, integrationTests/DonationMatchingTest.php, integrationTests/bootstrap.php, phpstan-baseline.neon, phpstan.neon, src/Application/Actions/Donations/Update.php, src/Application/Actions/GetPaymentMethods.php, src/Application/Actions/Hooks/Stripe.php, src/Application/Commands/LockingCommand.php, src/Application/Commands/WriteSchemaFile.php, src/Application/RedisMatchingStorage.php, src/Application/Settings.php, src/Domain/CampaignRepository.php, src/Domain/DoctrineDonationRepository.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Domain/PostCode.php, src/Domain/PostalAddress.php, src/Domain/RegularGivingService.php, src/Migrations/Version20220404153900.php, src/Migrations/Version20220404165640.php, src/Migrations/Version20241128165753.php, tests/Application/Actions/Donations/ResendDonorThanksNotificationTest.php, tests/Application/Commands/RedistributeMatchFundsTest.php, tests/Application/Commands/UpdateCampaignsTest.php, tests/Domain/CountryTest.php, tests/Domain/DonationTest.php, tests/Domain/InMemoryDonationRepository.php, tests/Domain/RegularGivingServiceTest.php
Enable stricter checking with phpstan and https://github.com/phpstan/phpstan-strict-rules
=> Phpstan extra strict

src/Domain/DonationService.php, tests/Domain/DonationServiceTest.php, tests/TestLogger.php
This is now passing but may need a bit more work to understand why we're logging the same things twice and adding comments to test
=> MAT-421: Restore skipped test

src/Application/Actions/Hooks/StripePaymentsUpdate.php, src/Domain/Donation.php, src/Domain/DonationService.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Hooks/StripePaymentsUpdateTest.php, tests/Application/DonationTestDataTrait.php, tests/Application/Messenger/Handler/StripePayoutHandlerTest.php, tests/Domain/DonationRepositoryTest.php, tests/TestData/StripeWebhook/ApiResponse/ch_list_success.json, tests/TestData/StripeWebhook/ch_succeeded.json
As there are quite a lot of changes already in https://github.com/thebiggive/matchbot/pull/1362 that I'd like to get into prod without more delay than necessary I think I'd wait until that's deployed before merging and testing this on staging.
Changes here may also end up conflicting with https://github.com/thebiggive/matchbot/pull/1365
=> MAT-395: Change stripe capture method to automatic_async

src/Migrations/Version20250522120626.php
Best to keep environments as similar as we can
=> Drop new view that exists in regtest but not staging

src/Domain/Donation.php, src/Migrations/Version20250603143120.php, tests/Domain/DonationTest.php
=> MAT-421 – patch out of sync `totalPaidByDonor` for `amount`-patched donation

app/routes.php, src/Application/Actions/MetaCampaigns/Get.php, src/Application/Commands/CreateFictionalData.php, src/Application/HttpModels/Campaign.php, src/Application/HttpModels/MetaCampaign.php, src/Domain/CampaignService.php, src/Domain/MetaCampaign.php, src/Domain/MetaCampaignSlug.php
=> MAT-405: Create meta-campaign GET handler

composer.json, composer.lock, src/Application/Messenger/DonationUpserted.php, src/Domain/PersonId.php
Primarily updating to get thebiggive/messages v3.3.2 which adds message group IDs for this message type.
=> Update libs to make email verification token handling quicker when the queue's busy

app/dependencies.php, composer.json, composer.lock, integrationTests/CampaignRepositoryTest.php, src/Application/Actions/Campaigns/Search.php, src/Domain/CampaignRepository.php
* [support offset & limit, matching SF defaults](https://github.com/thebiggive/matchbot/pull/1448/commits/04c84579ad3b88efd90a0608289868b4ad912b21)
* [support most filter fields, including term partial match against the most important fields and sort by relevance](https://github.com/thebiggive/matchbot/pull/1448/commits/4627c04248641d43d6a5bfa2309322da50409059)
=> MAT-413 – next campaign search steps

src/Application/Actions/Charities/Put.php, src/Application/Actions/Charities/UpsertMany.php
It makes more sense to flag this in Salesforce if anywhere.
=> MAT-405: Remove non-production feature flaging for charities upsert

src/Application/Persistence/RegularGivingMandateEventSubscriber.php
To reduce the likelihood of record contention issues on the receiving side, similarly to what we do with Donations
=> MAT-441 – slightly delay pushing active Mandates to Salesforce

integrationTests/DonationPersistenceTest.php, schema/Donation.sql, src/Application/Actions/Donations/Update.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Domain/PaymentCard.php, src/Migrations/Version20250729165929.php, tests/Domain/DonationRepositoryTest.php
Step towards privitising Donation::deriveFees
=> MAT-443: Save payment card details (brand & country) on donations

src/Application/Actions/Campaigns/Get.php, src/Application/Actions/Campaigns/Put.php, src/Application/Actions/Campaigns/Search.php, src/Application/Actions/Campaigns/UpsertMany.php, src/Application/Actions/MetaCampaigns/Get.php, src/Application/Environment.php, src/Domain/CampaignService.php
Releasing the main part of MAT-405 to production !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=> Main <- develop

codecov.yml
* Set a project target of 70% with substantial leniency before it blocks – https://docs.codecov.com/docs/common-recipe-list#set-status-checks-to-block-coverage
* Make patch coverage informational only – https://docs.codecov.com/docs/common-recipe-list#set-non-blocking-status-checks
* Turn off GitHub annotations – https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations-via-yaml
=> First pass reconfiguring Codecov

app/routes.php, src/Application/Actions/Sitemap.php, src/Application/HttpModels/MetaCampaign.php, src/Domain/CampaignService.php, src/Domain/MetaCampaign.php, src/Domain/MetaCampaignRepository.php, tests/MatchBot/Application/Actions/SitemapTest.php, tests/MatchBot/Domain/MetaCampaignTest.php, tests/TestCase.php
Reverts thebiggive/matchbot#1572
To merge when we've hidden anything we need to hide (very old inaccurate campaign data)
=> Revert "Revert "DON-984: Include metacampaigns in sitemap""

src/Application/Commands/PatchFunds8Oct.php, src/Domain/CampaignFundingRepository.php
And flush EntityManager more proactively
=> MAT-460 – fix zeroBigGiveWgmf25Funding() issues
