thebiggive/matchbot

deploy/secrets_entrypoint_tasks.sh, deploy/secrets_entrypoint_web.sh
In its original position it seemed to be unhappy in the case where the DB was not yet bootstrapped
from the first migrate run
=> Develop -> master - MAT-16 - move `doctrine:ensure-prod` later

deploy/secrets_entrypoint_tasks.sh, deploy/secrets_entrypoint_web.sh
This reverts commit 888d7a05
This was a red herring - the issue was a missing piece of config allowing ECS containers to read the
configuration secrets. Putting this back where it was should mean we catch any misconfigurations
earlier.
=> Develop -> master - Revert "MAT-16 - move `doctrine:ensure-prod` later"

.env.example, src/Client/Common.php, src/Client/Donation.php, src/Domain/DonationRepository.php, src/Domain/SalesforceWriteProxyRepository.php
* Implement Doctrine retries for non-realtime pieces: The 2 failures in the most recent load test were 1 on each of the two `flush()` calls migrated here. With this happening in rare edge cases it should be safe - and prudent - to retry after this type of error.
* Rationalise attempts to update push proxies not yet created successfully
* Add a feature flag to skip pushing donations to Salesforce
=> MAT-15 - error resilience + smarter Salesforce push options

src/Application/Actions/Hooks/DonationUpdate.php, src/Application/HttpModels/Donation.php, src/Domain/Donation.php, src/Migrations/Version20191119154404.php
* MAT-23 - add field to the Donation domain model and migrate the schema
* MAT-24 - support receiving the value in webhook and persist it
* MAT-25 - return field in GETs by including it in `Donation::toApiModel()`
* MAT-26 - send field from Salesforce client due to same change, as `toHookModel()` starts with the API model
=> MAT-22 - add tip support

src/Domain/CampaignFundingRepository.php, src/Domain/FundRepository.php
* MAT-30 - fix unexpected CampaignFunding available amount resets
* MAT-30 - fix crashes if we get unexpected `null` fund amounts
* Explain what's going on with defined and arbitrary allocation orders
=> MAT-30 - fund update fixes + inline docs

src/Application/Commands/ExpireMatchFunds.php, src/Domain/Donation.php
* Fix champion match amounts being sent to Salesforce in reserved contexts instead of only when confirmed
* Don't push Pending donations to Salesforce after expiry, as this provides no new information and currently crashes the webhook receiver
=> MAT-36 - fix Salesforce-pushed donation data

composer.json, matchbot-cli.php, src/Application/Commands/RetrospectivelyMatch.php, src/Domain/Donation.php, src/Domain/DonationRepository.php
Looks for:
* any donation in the past 48 hours when the task runs
* to a matched campaign
* with no funding withdrawals or a total less than the donation total
And then attempts matching allocation following the standard logic, which now accounts for any existing withdrawals for the donation.
=> MAT-43 - add a task to retrospectively match donations

src/Application/Actions/Donations/Create.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, tests/Domain/DonationTest.php
* MAT-50 - only allocate match funds after a Donation is persisted successfully - this should fix edge cases where funds' totals can get out of sync with donation allocations
* MAT-50 - do amount validation inside `setAmount()` and simplify surrounding validation logic
* MAT-50 - add logs; make validation error output more helpful
* MAT-46 - return 400 Bad Request if any of the 3 donation init boolean fields are missing or null
=> MAT-50, MAT-46 - validation fixes

composer.json, matchbot-cli.php, src/Application/Commands/HandleOutOfSyncFunds.php
Reduce risk of running the wrong one mistakenly
=> Rename & separate out Composer check/fix commands

composer.json, src/Application/Commands/HandleOutOfSyncFunds.php, src/Application/Matching/Adapter.php, src/Application/Matching/DoctrineAdapter.php, src/Application/Matching/LockingRedisAdapter.php, src/Application/Matching/OptimisticRedisAdapter.php
* `getAmountAvailable()` based on the live matching adapter, not always the DB copy: When using either Redis adapter, this should reduce the frequency with which the sync commands report spurious mis-matches because new data hasn't finished being persisted to the database.
* Fix typo in updated sync Composer commands
=> Sync command tweaks

src/Application/Actions/Donations/Cancel.php, tests/Application/Actions/Donations/CancelTest.php
Stricter handling at the Action level should fix this crashing with the new HTTP model type constraints.
This PR also adds a unit test for this invalid data case and adds a much better, more realistic happy path
test case for valid cancellations.
=> MAT-59 - add validation for missing `status` on cancellation

composer.json, matchbot-cli.php, src/Application/Commands/UpdateCampaigns.php, src/Domain/DonationRepository.php, tests/Application/Commands/UpdateCampaignsTest.php
* clear result cache after creating/updating campaigns, en masse or individually
* skip the result cache for multi-donation lookups
* clear all 3 Doctrine caches on startup
=> MAT-77 – fix result cache handling

.env.example, app/dependencies.php, app/routes.php, app/settings.php, composer.json, composer.lock, phpunit.xml, src/Application/Actions/Donations/Create.php, src/Application/HttpModels/DonationCreate.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, src/Migrations/Version20200713104818.php, tests/Application/Actions/DonationTestDataTrait.php, tests/Application/Actions/Donations/CreateTest.php, tests/Domain/DonationTest.php
* set up Stripe library + service config
* introduce a required `psp` field for Donations and populate existing Donations' with 'enthuse'
* for 'stripe' Donations just created, make a Payment Intent, storing and returning the associated client secret
=> MAT-84 - add Stripe Payment Intent setup

src/Application/Actions/Donations/Create.php, src/Domain/Donation.php, tests/Application/Actions/Donations/CreateTest.php, tests/Domain/DonationTest.php
* give Donation a method to calculate the amount for the charity
* send this amount and Connected Stripe Account ID during Payment Intent setup
=> MAT-93 - calculate & send Stripe transfer data

src/Application/Actions/Donations/Create.php, src/Domain/Charity.php, tests/Application/Actions/Donations/CreateTest.php
* fix possible crash when checking for Stripe Account ID
* fail gracefully when a Donation Create is attempted in Stripe mode with no Stripe Account ID set
=> MAT-93 - Stripe Account ID considerations

src/Application/HttpModels/Donation.php, src/Client/Donation.php
This should fix e.g. cancellations in cases where these values
were never set but the Action still returns the updated Donation
object using this model
=> Make more HTTP Donation model properties optional

.env.example, src/Client/Donation.php, src/Domain/DonationRepository.php, src/Domain/SalesforceWriteProxy.php, src/Domain/SalesforceWriteProxyRepository.php, tests/Domain/DonationRepositoryTest.php
* MAT-125 - unqueue old donations in sandboxes
* MAT-125 - test the 3 update push scenarios
* MAT-125 - reduce cases where we double-push to Salesforce
* MAT-126 - update local example SF timeout
=>  MAT-125 - unqueue old donations in sandboxes + related

.env.example, src/Application/Commands/ExpireMatchFunds.php, src/Application/Commands/HandleOutOfSyncFunds.php, src/Application/Matching/OptimisticRedisAdapter.php, src/Domain/FundingWithdrawalRepository.php, tests/Application/Commands/HandleOutOfSyncFundsTest.php
* try to fix adapter's `getAmountAvailable()` used by the check command in cases where campaigns are not being frequently accessed – should resolve numerous spurious reported under-matches
* support excluding known historic mismatches from the same command – will let us assess new data without the 1 known CC19 discrepancy confusing monitoring
* replace all non-integer casts with bcmath functions – should resolve rare out-by-£0.01 bug
* show zeroes clearly in out of sync fund check command
=> MAT-121 – matching stability & script enhancements

.env.example, app/routes.php, app/settings.php, phpunit.xml, src/Application/Actions/Hooks/Stripe.php, src/Application/Actions/Hooks/StripeChargeUpdate.php, src/Application/Actions/Hooks/StripePayoutUpdate.php, src/Application/Actions/Hooks/StripeUpdate.php, src/Migrations/Version20201119205321.php, tests/Application/Actions/DonationTestDataTrait.php, tests/Application/Actions/Hooks/StripeChargeUpdateTest.php, tests/Application/Actions/Hooks/StripePayoutUpdateTest.php, tests/Application/Actions/Hooks/StripeTest.php
* split webhook types into separate endpoints
* log error on `payout.failed`
* skip non-livemode events in Production
* update 3 Mousetrap Theatre missed donations to Paid status and mark for re-pushing to Salesforce
=> MAT-124, MAT-132 – Stripe webhook updates

src/Application/Actions/Donations/Update.php, src/Application/Actions/Hooks/DonationUpdate.php, src/Application/Actions/Hooks/StripeChargeUpdate.php, src/Domain/DonationRepository.php, tests/Application/Actions/Hooks/DonationUpdateTest.php
Should eliminate a rare edge case where the same match funds can be released twice.
Also remove a nonsensical match release after success clause in the Stripe hook.
=>  MAT-143 - fix the order of operations during donation cancellation and hook updates

src/Application/Commands/RetrospectivelyMatch.php, src/Domain/DonationRepository.php
So we can:
* assess how close the retrospective match command is to finishing, and
* ensure matching is allocated more intuitively within the given date range
=> Set order of donations to evaluate for possible matching explicitly

src/Domain/Donation.php, src/Domain/SalesforceProxy.php, src/Domain/SalesforceWriteProxy.php, src/Domain/SalesforceWriteProxyRepository.php, tests/Domain/DonationRepositoryTest.php
* for post-error records over 30 seconds old, create-then-update in one go
* for newer ones, log an error but leave them ready to pick up next time
=> MAT-170 - hopefully fix create-then-update logic for good!

composer.json, src/Application/Commands/ResetMatching.php, tests/Application/Commands/ResetMatchingTest.php
* rely just on migrations for schema structure rebuild; reset the migrations table to 'first' first so this can work
* make `ResetMatching` command handle empty database case
=> MAT-174 reset fixes

matchbot-cli.php, src/Application/Commands/UpdateCampaigns.php, tests/Application/Commands/UpdateCampaignsTest.php
Handle scenario where a charity with a previously approved campaign is no
longer in a state where they should be allowed to receive donations.
=> MAT-177 - error log instead of re-throwing exception when trying to update a 'missing' campaign in Production

composer.json, composer.lock
Brings in library update https://github.com/thebiggive/LosRateLimit/pull/1/commits/d8785d2348f4c927e56dae9098fafc0ceee154aa
=> MAT-214 - use IPv6-safe cache keys for rate limiting

app/dependencies.php, composer.json, src/Application/Messenger/Handler/StripePayoutHandler.php, tests/Application/Messenger/Handler/StripePayoutHandlerTest.php, tests/TestData/StripeWebhook/ApiResponse/ch_list_with_invalid.json
Reduce the date range window for parent Stripe account Transfer checks
from the original 22 days to +/- 10 seconds from the actual earliest and
latest charge created times associated with the payout
=> MAT-218 - improve payout processing efficiency slightly; increase max payout handler runtime to 2 hours

src/Application/Messenger/Handler/StripePayoutHandler.php, tests/Application/Messenger/Handler/StripePayoutHandlerTest.php
By caching this for ~14 hours we can hopefully get these messages processed in
a more reasonable time after the first one each day
=> MAT-218 - save Stripe transfer ID -> source charge ID in a Redis hash

src/Domain/Donation.php, tests/Domain/DonationTest.php
Also fall back to blank string to avoid a type crash should home postcode be `null`.
=> MAT-227 - handle overseas donations correctly

matchbot-cli.php, src/Application/Commands/LockingCommand.php, src/Application/Commands/UpdateCampaigns.php, tests/Application/Commands/ClaimGiftAidTest.php, tests/Application/Commands/ExpireMatchFundsTest.php, tests/Application/Commands/HandleOutOfSyncFundsTest.php, tests/Application/Commands/PushDonationsTest.php, tests/Application/Commands/ResetMatchingTest.php, tests/Application/Commands/RetrospectivelyMatchTest.php, tests/Application/Commands/UpdateCampaignsTest.php
CloudWatch Events run "at least once" (https://stackoverflow.com/a/39794141/2803757)
and we have observed the every-minute funds expiry process getting
invoked twice within a couple of seconds several times over late 2021/
early 2022.
If this happens regularly we should know about it, so a warning log that
shows up on dashboards is appropriate. But occasional overlaps are harmless
and we don't want the noise of *error* alarms from this. As we treat all
non-0 return codes from commands as errors, this update has locking commands
return 0 OK once they have logged their warning in this scenario.
=> Return 0 OK and log a warning if a command runs twice

src/Domain/Donation.php, tests/Application/Actions/Donations/CreateTest.php, tests/Domain/DonationTest.php
Also remove workaround for previous data issue MAT-168
=> MAT-234 – temporarily silently strip out ';;' from email addresses

src/Application/HttpModels/Donation.php, src/Domain/DonationRepository.php, tests/Domain/DonationRepositoryTest.php
* [MAT-243 – catch missing amounts + currencies early](https://github.com/thebiggive/matchbot/commit/0c537ec3d18caaf7d34a484d8c73619cb34e9e81)
* Test `DonationRepository::buildFromApiRequest()` success and additional failure mode
* [MAT-243 – drop missing currency fallback support from `DonationRepository::buildFromApiRequest()` and donation HTTP model](https://github.com/thebiggive/matchbot/commit/f64a2e1256c57e02977d737e3029886fe49dfdf9)
=> MAT-243 – better validation and tighter currency code requirements

src/Application/Actions/Action.php, src/Application/Actions/Donations/Create.php, src/Client/Donation.php, tests/Application/Actions/Donations/CreateTest.php
Spotted while testing with Dom today that HTTP 200 isn't what the
current API contract says will be returned.
=> Make successful donation creates respond with HTTP 201 as documented

app/dependencies.php
It's not totally clear what the default/ previous effective value was but some tasks
seem to give up with timeouts after only a few seconds at most, so this seems a reasonable
step to help isolate issues and perhaps fix slow task startups.
=> Give Redis / ElastiCache a full 15s for connection

app/dependencies.php
This reverts commit 35af02863ad80e3bbf1a02e82de08f7e00a8fc98.
Reversing the change to reduce the risk of unnecessarily adding a regression or a shorter timeout, and instead move things back to what we did back in April when this was last stable.
=> MAT-249 – Revert "Give Redis / ElastiCache a full 15s for connection"

.circleci/config.yml, Dockerfile, src/Application/Actions/Status.php, tests/Application/Actions/StatusTest.php
Also expand unit tests to cover the healthy case
=> MAT-262 – expand `Status` to test Doctrine ORM proxies' presence

src/Application/Handlers/HttpErrorHandler.php
Now we are passing in the correct service, Staging is logging every not found request with a high severity log. We definitely need to exclude simple 404s and so far it looks reasonable for all `HttpException` to be excluded from logging at this level.
=> Only include non-user-error-HTTP exceptions for logging as `.ERROR`

src/Application/Actions/Donations/Update.php, src/Application/Actions/Hooks/StripeChargeUpdate.php, src/Application/Handlers/HttpErrorHandler.php, src/Domain/DonationRepository.php, src/Domain/SalesforceWriteProxyRepository.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Actions/Hooks/StripeChargeUpdateTest.php
For both Stripe charge and donor initiated updates. Use pessimistic locks for both to start out.
=> MAT-260 – pessimistic lock all database donations

src/Domain/Donation.php, src/Domain/DonationRepository.php, src/Migrations/Version20221025044553.php, src/Migrations/Version20221030095831.php
Work around Production update being too slow to complete during a deploy
=> MAT-267 – fix donations with no `paymentMethodType` pre-push and not in a migration

src/Application/Actions/Donations/Update.php, tests/Application/Actions/Donations/PaymentIntentUpdateAttemptTwicePromise.php, tests/Application/Actions/Donations/UpdateTest.php
When Stripe object lock acquisition takes two goes, and then the second Payment Intent update fails due to capture being done, and we have no fee change to send, this can just be an `INFO` log.
=> MAT-276 – fix log error noise in new edge case of an edge case

src/Domain/DonationRepository.php
Missing donations are expected e.g. when a sandbox is handling Stripe hooks, as Stripe have only 1 test mode. And in all cases, a missing item in the first find call should return `null` instead of crashing.
=> MAT-260 – fix null handling in new repo helper

app/dependencies.php, src/Application/Messenger/Handler/StripePayoutHandler.php, tests/Application/Messenger/Handler/StripePayoutHandlerTest.php
* Stripe payout.paid message consumer: use database transactions as required for object locks
* Symfony Messenger general: Provide a non-null logger to message middlewares
=> MAT-289 – Stripe payout.paid message consumer fix and logging config improvement

src/Application/Commands/PushDonations.php, src/Domain/SalesforceWriteProxyRepository.php, tests/Application/Commands/PushDonationsTest.php
Tiny refinement following trying to explain this method today! The old name is confusing both in looking too much like it might relate to donation status when in a Donation-related context, and in saying "all" when it has a limit by default
=> Write proxy method rename

.circleci/config.yml, Readme.md, composer.json, integrationTests/CharityRepositoryTest.php, integrationTests/IntegrationTest.php, integrationTests/PingSmokeTest.php, integrationTests/bootstrap.php, phpunit-integration.xml, psalm.xml, src/Migrations/Version20230117173337.php
Sorry this is in matchbot and the Jira was `id` - it felt like it was most urgent to get this done for `matchbot`. If this is approved it should be pretty simple to copy the setup into `identity` and run similar checks there.
The other idea suggest in the ticket that isn't done yet but could be is checking that `migrations:diff` doesn't attempt to make any changes if run in Circle - i.e. that whatever changes it would make have already been committed into a migrations file.
=> ID-32: Run tests integrated with MySQL in CircleCI

api.yaml, src/Application/Actions/Donations/Update.php, src/Application/Actions/Hooks/StripeChargeUpdate.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, src/Domain/DonationStatus.php, tests/Domain/DonationTest.php
Putting the docs here means (at least in PHPStorm) that we can hover over any line of code that mentions a status to see the documentation:
=> Bg2-2296 document donation statuses ii

tests/Application/Actions/DeletePaymentMethodTest.php
Stops every autoload generation from showing a warning
=> Fix test at wrong namespace

app/settings.php, src/Application/Actions/Hooks/StripePayoutUpdate.php, tests/Application/Actions/Hooks/StripePayoutUpdateTest.php
* Make it explicit which environment a notification is coming from
* Move implicit Slack configuration requirement nearer to other settings
=> MAT-287 – clearer failed payout notifications

tests/Application/Commands/DeleteStalePaymentDetailsTest.php, tests/TestData/StripeWebhook/ApiResponse/pm.json
Could go further and extracted repeated code from between the two tests into either setup or just new private methods.
Another thing I haven't fixed is the union types - quite a few things are using unnecessary union types with ObjectProphecy, when it's always one side of the union or the other.
=> Mat 295 simplify unit test

src/Application/Commands/DeleteStalePaymentDetails.php, tests/Application/Commands/DeleteStalePaymentDetailsTest.php, tests/Application/StripeFormattingTrait.php
Changes the logic of the payment method detacher to work based on newly complete metadata in stripe - and also adds an extra metadata field to stripe to track which customer accounts the command has operated on them so that it won't find the same account in search next time it runs.
=> MAT-295: Detatch payment cards from passwordless accounts

psalm-baseline.xml, src/Application/Actions/Donations/Update.php, src/Domain/DonationRepository.php, tests/Application/Actions/Donations/UpdateHandlesLockExceptionTest.php, tests/Application/Actions/Donations/UpdateTest.php
Also:
* Reduce `Update`'s database access when we can fail validation earlier
* Use UUID over ID a bit more clearly & consistently in logs etc.
=> MAT-302 – fix Update lock wait recovery

integrationTests/DonationPersistenceTest.php, psalm-baseline.xml, src/Application/Actions/Donations/Update.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/UpdateHandlesLockExceptionTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Actions/Hooks/StripeChargeUpdateTest.php, tests/Application/Commands/ExpireMatchFundsTest.php, tests/Application/DonationTestDataTrait.php, tests/Application/Persistence/RetrySafeEntityManagerTest.php, tests/Domain/DonationRepositoryTest.php, tests/Domain/DonationTest.php
Fairly substantial refactoring involved in this PR, must of it done with the PhpStorm tools, and actually the changes in production code are minimal so it's pretty safe, it's mostly changes in test code. The main reason is that the new requirement has the maximum donation amount dependant on the payment method type, and so the donation class can only enforce that if it doesn't allow them to be set separately, or at least doesn't allow the method to be changed after the amount is set.
Our site doesn't actually support changing the amount on an existing donation, so there's no need for the class to support it. Now amount, currency code and payment method type are all required params of the domain donation constructor. In production we only ever construct a donation by calling …
=> DON-800: Increase donation limit for donation account users to £200k

psalm-baseline.xml, src/Domain/Donation.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/DonationTestDataTrait.php, tests/Domain/DonationTest.php
Frontend already refuses tips for these donations, but I think that logic may been only in the HTML template:
https://github.com/thebiggive/donate-frontend/blob/4a1a0788441b796394bbfd1d7d1381dffcff5811/src/app/donation-start/donation-start-form/donation-start-form.component.html#L63
=> DON-772: Stop accepting tips on customer balance based donations

integrationTests/DonationPersistenceTest.php, src/Application/Actions/Hooks/StripeChargeUpdate.php, src/Client/Donation.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, src/Domain/DonationStatus.php, src/Migrations/Version20230622095211.php, tests/Domain/DonationTest.php
Because the salesforce part isn't done yet, (see https://github.com/thebiggive/salesforce/pull/1316) the one line here that does the actual sending of new data to SF is commented out. But the code to pull it from Stripe into Matchbot's DB etc should be fine to start running whenever we want to deploy.
=> BG2-2306: Prepare to send refund timestamp to salesforce

composer.json, composer.lock, psalm-baseline.xml, src/Application/Messenger/Handler/StripePayoutHandler.php
Only changes to PHP code are deleting an unecassary and misleading docblock. There's one new issue in the baseline relating to unchanged code where Psalm now detects a possible issue, I think it's not anything we need to worry about though.
For Psalm changes see everything after 5.7.4 and up to and including 5.13.0 at https://github.com/vimeo/psalm/releases
=> Upgrade Psalm to latest release 5.13.0

src/Application/HttpModels/DonationCreate.php, src/Domain/Donation.php, tests/Domain/DonationTest.php
Currently the donation has to be created without these details and then they can be added later in a PUT request.
=> DON-706: Allow setting donor name and email on new donations

integrationTests/CreateDonationTest.php, integrationTests/IntegrationTest.php, src/Domain/Donation.php, tests/Domain/DonationTest.php
We've never seen a donation with a negative tip, and the front end doesn't allow it, but best to block it just in case anyone tries or somehow creates one by mistake.
=> MAT-316: Prevent donations with negative tip

app/routes.php, psalm.xml, src/Application/Actions/Donations/Confirm.php, src/Application/Fees/Calculator.php, tests/Application/Actions/Donations/ConfirmTest.php, tests/Application/Fees/CalculatorTest.php
Introduces a new route at `/donations/{donationId:[a-z0-9-]{36}}/confirm`. Frontend should post to this to indicate when a donor is ready to pay, at which point matchbot will pass the message on to Stripe.
=> DON-893: Allow confirming payment methods on server side from matchbot

integrationTests/DonationPersistenceTest.php, psalm-baseline.xml, src/Application/Actions/Donations/Create.php, src/Domain/Donation.php, src/Migrations/Version20230925121435.php, tests/Application/Actions/Donations/CreateTest.php, tests/Domain/DonationTest.php
Not needed in future when donations are always confirmed from matchbot not from the client
** DO NOT MERGE UNTIL AFTER https://github.com/thebiggive/donate-frontend/pull/1302 IS DEPLOYED TO PROD **
=> MAT-317: Remove Donation.clientSecret property

src/Domain/CampaignRepository.php, src/Domain/Charity.php, tests/TestCase.php
SF ID has to be set for all charities. The DB doesn't enforce this, but if we save a charity with no SF ID then we won't find it when we need it and we'll try to pull it from SF again - and get a constraint violation error on the duplicate Stripe ID.
This bug has not been in production - I found it on my local
=> MAT-321: Fix bug introduced in commit 037a7cf22

src/Domain/Campaign.php, src/Migrations/Version20231010105436.php
Having a campaign without a charity might be the cause of a crash on attempt to persist a donation. This may bring any crash earlier and make it easier to understand deal with.
I have checked the production database, there are currently no campaigns without charities, i.e. the following returns the empty relation:
```
SELECT * from Campaign where Campaign.charity_id IS NULL;
```
=> MAT-321: Prevent persisting any Campaign without a Charity ID

app/repositories.php, app/routes.php, composer.json, composer.lock, integrationTests/CreateDonorAccountTest.php, src/Application/Actions/DonorAccount/Create.php, src/Application/Assertion.php, src/Application/AssertionFailedException.php, src/Application/Auth/PersonWithPasswordAuthMiddleware.php, src/Domain/DonorAccount.php, src/Domain/DonorAccountRepository.php, src/Domain/EmailAddress.php, src/Domain/StripeCustomerId.php, src/Domain/TimestampsTrait.php, src/Migrations/Version20231016113352.php, src/Migrations/Version20231016115215.php, src/Migrations/Version20231016141922.php, src/Migrations/Version20231016160140.php
Once this is in Matchbot, frontend should be able to call it to create a donor account when required. Then stripe can call matchbot to say cash has been transferred to an account, matchbot will be able to look up the account and finally use mailer to email the account holder.
=> MAT-306: Allow creating donor accounts

integrationTests/DonationPersistenceTest.php, integrationTests/StripeCancelsDonationTest.php, src/Application/Actions/Donations/Update.php, src/Domain/DonationRepository.php, src/Domain/DonationStatus.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Domain/DonationRepositoryTest.php
By referencing the enum each time instead of repeating the literal we allow static analysers to check that we haven't typo'd, get earlier runtime crashes in case of error, and allow clicking through to read documentation of each status case from anywhere it's referenced.
The one place were I haven't done this is in migration files, as those need to keep the same literal string value even if we change or remove the DonationStatus case in future - migrations are basically write-only files and shouldn't depend on things that we might change.
=> Refactor - reduce duplication of string literal status names

src/Application/Actions/DonorAccount/Create.php, src/Application/Assert.php, src/Application/LazyAssertionException.php, src/Domain/DonorAccount.php, src/Domain/DonorAccountRepository.php, src/Domain/DonorName.php, src/Domain/EmailAddress.php, src/Migrations/Version20231018104935.php
This does two things, both about rejecting unwanted requests for creating donor accounts:
- If we get a request without all required data, we now return a 400 response instead of an alarming 500.
- If we get a request to create a duplicate account (i.e. with a stripe customer ID we've already got an account for) we reject that as well, with a 400, where previously we would have put the dupe into our DB.
=> MAT-306 - improve handling of bad requests

src/Application/Handlers/HttpErrorHandler.php
`getTraceAsString` only gives us all the *previous* stack frames before the one that actually has the `throw` statement. Using `getFile` and `getLine` will tell us exactly where the throw expression is that threw the exception.
=> BG2-2297: Add erroring file and line number to error logs

src/Domain/Money.php
Now that we're using this for balances as well as transfers it's reasonable for it to be zero sometimes.
=> MAT-306: Allow money to be zero

src/Application/PSPStubber.php
Reverts thebiggive/matchbot#669
We are using '1', and '0', not 'true' and 'false'.
=> Revert "Only bypass stripe if BYPASS_PSP is 'true' (not 'false')"

src/Application/Commands/PatchHistoricNonDefaultFeeDonations.php
The bugfix for new donations is not yet deployed, so we'll need the patch script to include donations created today and up until the point we fully deploy the bugfix. Hoping that will be before Thursday.
Having the scope extend a little beyond the time the fix is deployed is not a problem.
=> MAT-331: Increase scope for patching incorrect donation data

tests/Application/Fees/CalculatorTest.php
Before: https://output.circle-artifacts.com/output/job/4fc0ad64-f1e6-46d9-82f2-556a44616a33/artifacts/0/reports/infection.html#mutant/Application/Fees/Calculator.php
After: https://output.circle-artifacts.com/output/job/53448e1d-41d9-4bb4-a36d-e7dd796178ad/artifacts/0/reports/infection.html#mutant/Application/Fees/Calculator.php
Not as dramatic an increase in mutation score as I'd like - had a bit of trouble seeing how to kill the `BCMath` mutants which is most of them, and thought it's maybe not that important.
Also would like to simplify the class so it needs less tests instead of just adding tests, which we could do by making the settings hard-coded instead of having it pull in settings and also avoid using the environment variables. But that's probably something for outside of the …
=> Mat 326 unit test calculator

tests/Domain/DonationTest.php
I think this is probably enough tests for now in the Donation class. Although there are still quite a few mutants none seem to be in particularly complicated code, and some will naturally be dealt with if we test other classes that depend on Donation.
Only test file changed so no way for this to affect prod directly.
Mutation results as at commit 7abad : https://output.circle-artifacts.com/output/job/c37c9b14-91a2-476e-9804-e8e070b5c380/artifacts/0/reports/infection.html#mutant/Domain/Donation.php
=> Mat 326: More tests for Donation class

src/Application/Actions/Donations/Create.php
Run match fund release in a new "matching adapter transaction". And also log the original \Throwable message earlier, separately, just in case.
=> MAT-336 – improve donation Create edge case recovery

composer.json, src/Application/Commands/HandleOutOfSyncFunds.php, tests/Application/Commands/HandleOutOfSyncFundsTest.php
Reverts thebiggive/matchbot#706 (and connected)
This temporary Command mode has now been used & isn't needed again.
=> Revert "MAT-338 – add temporary out of sync funds mode, '2023-11-30-patch'"

src/Migrations/Version20231207104909.php
Normally migration files are write-only and we don't edit old ones, but as this only affects productio and it has not yet been deployed there we can get away with editing the existing file.
=> CLA-34 - Remove gift aid from additional donation.

tests/Application/Actions/DeletePaymentMethodTest.php, tests/Application/Actions/GetPaymentMethodsTest.php, tests/Application/Actions/Hooks/StripePaymentsUpdateTest.php, tests/Application/Actions/UpdatePaymentMethodTest.php, tests/Application/Commands/DeleteStalePaymentDetailsTest.php, tests/Application/Messenger/Handler/StripePayoutHandlerTest.php
Looks like these have been erroring due to the deprecation of dynamic properties in PHP 8.2
=> Fix mutation tests

.circleci/config.yml, Dockerfile, composer.json, composer.lock, docker-compose.yml, integrationTests/IntegrationTest.php
Since this is deployed as a container with a PHP runtime included it doesn't make sense to try to support multiple PHP versions at the same time as I was doing before the holiday.
=> BG2-2520: Replace PHP 8.2 with 8.3

src/Application/Commands/DeleteStalePaymentDetails.php, tests/Application/Commands/DeleteStalePaymentDetailsTest.php
Tested on my local by running `./matchbot matchbot:delete-stale-payment-details`, which seems to be working to update the test copy of this account. Once this is deployed to prod it should update the real thing, removing any set representative so that we can set a new one manually during the grace period.
=> BG2-2548: Clear account rep

src/Application/Actions/Hooks/StripePaymentsUpdate.php
This may have been broken recently, but on my local I was getting an exception for non-card (i.e. donation funds) payments:
[2024-01-22T15:24:59.419989+00:00] matchbot.ERROR: Exception: Stripe Notice: Undefined property of Stripe\StripeObject instance: card (etc)
Tested the new version and it works both with cards and non cards - we still capture the full details of the card.
=> DON-954: Fix processing of web hoooks for non-card payments

src/Application/Commands/DeleteStalePaymentDetails.php
The previous version ran in prod but didn't actually do anything useful I realise now the `updateAttributes` function was just for updating the attributes in the object in memory on the PHP side - it doesn't actually send anything to Stripe. `updatePerson` is what is recommended at
https://stripe.com/docs/connect/update-verified-information?locale=en-GB#change-the-account-representative
=> BG2-2548: Fix stripe update script

src/Application/Commands/DeleteStalePaymentDetails.php, tests/Application/Commands/DeleteStalePaymentDetailsTest.php
This reverts commit a62663310b4102e5196b3d3800e428ab0e66f8f3.
Clearing the account rep is not working with the code as it is, and it's triggering an alarm every 2 hours.
=> Revert "BG2-2548: Clear account rep"

.psalm/psalm-baseline.xml, composer.json, composer.lock
psalm to 5.19.1, doctrine-psalm-plugin to 2.9.0
Several instances of the new RiskyTruthyFalsyComparison issue added to baseline.
See https://psalm.dev/docs/running_psalm/issues/RiskyTruthyFalsyComparison/ for description of this issue and how we could resolve it instead of ignoring it as I've done here.
Output from the new Psalm version before errors were added to baseline:
```
barney@barney-l-xps:~/projects/matchbot$ d vendor/bin/psalm
Target PHP version: 8.3 (inferred from current PHP version) Enabled extensions: pdo, redis.
Scanning files...
Analyzing files...
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 261 (22%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 120 / 261 (45%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 180 / 261 …
```
=> NO-TICKET: Update Psalm & Doctrine Psalm Plugin

src/Application/Messenger/Handler/StripePayoutHandler.php, tests/Application/Actions/Donations/PaymentIntentUpdateAttemptTwicePromise.php, tests/Application/Messenger/Handler/StripePayoutHandlerTest.php, tests/TestData/StripeWebhook/ApiResponse/bt_list_only_retried_payout.json
This should ensure that for all future payouts, donations' status is updated after an earlier payout they were in failed but the latest payout's gone through.
=> CLA-37 – reconcile donations from retried payouts, setting them 'Paid'

src/Application/Messenger/Handler/StripePayoutHandler.php
This would make it easier to understand why our new checks are causing error logs occasionally on e.g. Staging.
=> Log connected account ID in error-ing payout webhook cases

composer.json, src/Application/Commands/ReconcilePastPayouts.php, src/Application/Messenger/Handler/StripePayoutHandler.php, tests/Application/Commands/ReconcilePastPayoutsTest.php, tests/Application/Messenger/Handler/StripePayoutHandlerTest.php, tests/TestData/StripeWebhook/ApiResponse/po_failed.json
* [check the Stripe API agrees payouts are "paid" before we update their donations' statuses](https://github.com/thebiggive/matchbot/pull/788/commits/330c0bc0fae395e0f4ce0f06b5166a285abcb98d)
[330c0bc](https://github.com/thebiggive/matchbot/pull/788/commits/330c0bc0fae395e0f4ce0f06b5166a285abcb98d)
* [add a temporary on-demand command `matchbot:reconcile-payouts` for historic payout edge cases](https://github.com/thebiggive/matchbot/pull/788/commits/606e6e1c9a82fbd444ebdbce7099551e327e2731)
[606e6e1](https://github.com/thebiggive/matchbot/pull/788/commits/606e6e1c9a82fbd444ebdbce7099551e327e2731)
=> CLA-37 – add payout status check & temporary command for processing old edge case payouts

integrationTests/DonationPersistenceTest.php, src/Application/Actions/Donations/Update.php, src/Domain/Donation.php, src/Migrations/Version20240315145404.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Domain/DonationTest.php
…hen donation is confirmed
We were already setting this to false during donation creation, so this should not change the user experience at all.
=> MAT-356: Continued

.circleci/config.yml, app/dependencies.php, composer.json, src/Application/Actions/Donations/Update.php, tests/Application/Actions/Donations/UpdateHandlesLockExceptionTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/TestCase.php
On my laptop:
Before:
```
vendor/bin/phpunit
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set
...............................................................  63 / 291 ( 21%) ...............................................S............... 126 / 291 ( 43%) ............................................................... 189 / 291 ( 64%) ............................................................... 252 / 291 ( 86%)
.......................................                         291 / 291 (100%)
Time: 00:04.181, Memory: 58.00 MB
```
After:
```
$ vendor/bin/phpunit
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set …
```
=> Let unit test suite run 326% faster

src/Application/Messenger/Handler/StripePayoutHandler.php, tests/Application/Messenger/Handler/StripePayoutHandlerTest.php
(cherry picked from commit 2745d6f11b0da79ed6149375b0d7e3c481092d74)
=> CLA-37 [main hotfix] – temporarily check charges up to 2 years for payouts

src/Application/Messenger/Handler/StripePayoutHandler.php
I think this can be reviewed without reopening the original issue / new QA as it only affects non-live log levels.
=> MAT-289 – remove a source of Stripe test mode error log noise introduced in Jan

src/Application/Actions/UpdatePaymentMethod.php, tests/Application/Matching/AdapterTest.php
Recently seen in alarms channel, doesn't indicate any general brokennnes.
=> Stop generating alarm on invalid card expiration month

docker-compose.yml, src/Application/Actions/Donations/Create.php, tests/Application/Actions/Donations/CreateTest.php
* Surface detail directly in Slack #stripe for whole team
* Return a 409 to reduce alarm noise for devs
=> MAT-365 – adjust messaging when a donation create attempt is for a Stripe account without capabilities

matchbot-cli.php, src/Application/Commands/HandleOutOfSyncFunds.php, src/Application/Commands/ScheduledOutOfSyncFundsCheck.php, tests/Application/Commands/HandleOutOfSyncFundsTest.php
Also move commands we're editing to the faster, non-deprecated attribute definition approach
=> MAT-369 – revert one-time parts of command changes

src/Application/Actions/Donations/Create.php, src/Domain/DonationService.php, tests/Application/Actions/Donations/CreateTest.php, tests/Domain/DonationServiceTest.php
Prevent problems from donation create actions continuing after persistent errors. And add a test for `Donations\Create` specifically to verify that errors are surfaced in API responses and that exactly the maximum # of attempts are made at persistence before giving up.
=> MAT-370 – fix `DonationService::runWithPossibleRetry()` silently swallowing errors

app/dependencies.php, consume-messages.sh, docker-compose.yml, integrationTests/RedistributeMatchingCommandTest.php, matchbot-cli.php, phpunit-integration.xml, src/Application/Actions/Donations/Confirm.php, src/Application/Actions/Donations/Create.php, src/Application/Actions/Donations/Update.php, src/Application/Actions/Hooks/StripePaymentsUpdate.php, src/Application/Commands/RedistributeMatchFunds.php, src/Application/Commands/RetrospectivelyMatch.php, src/Application/Messenger/DonationStateUpdated.php, src/Application/Messenger/Handler/DonationStateUpdatedHandler.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Domain/SalesforceWriteProxy.php, src/Domain/SalesforceWriteProxyRepository.php, tests/Application/Actions/Donations/ConfirmTest.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/UpdateHandlesLockExceptionTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Actions/Hooks/StripePaymentsUpdateTest.php, tests/Application/Commands/RedistributeMatchFundsTest.php, tests/Application/Commands/RetrospectivelyMatchTest.php, tests/Application/Messenger/Handler/DonationStateUpdatedHandlerTest.php, tests/Domain/DonationRepositoryTest.php, tests/Domain/DonationTest.php, tests/TestCase.php
Reverts thebiggive/matchbot#891 and adds a fix.
It's possible that we will see some level of errors from locks not being acquired and will need to add retries, but I think we can try it without first.
=> MAT-363 – re-apply work to queue Salesforce pushes, log more, and lock Donations proactively

.env.example, app/dependencies.php, app/routes.php, app/settings.php, src/Application/Actions/Charities/MarkUpdateRequiredFromSF.php, src/Application/Auth/SalesforceAuthMiddleware.php, src/Domain/Charity.php, src/Domain/CharityRepository.php, src/Migrations/Version20240709162518.php, src/Migrations/Version20240709162926.php, tests/Application/Auth/SalesforceAuthMiddlewareTest.php
For now matchbot will just record this mark in the db, and not do anything about it. Next step is doing something about it. Possibly I should have implemented them in the opposite order for more effective CI.
=> BG2-2620: Allow salesforce to mark a charity as needing update

integrationTests/DonationRepositoryTest.php, src/Application/Actions/Donations/Confirm.php, src/Application/Messenger/AbstractStateChanged.php, src/Application/Messenger/DonationUpserted.php, src/Client/Donation.php, src/Domain/Donation.php, src/Domain/DonationRepository.php, src/Domain/SalesforceWriteProxyRepository.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Actions/Donations/UpdateHandlesLockExceptionTest.php, tests/Application/Commands/RedistributeMatchFundsTest.php, tests/Application/Messenger/Handler/DonationUpsertedHandlerTest.php, tests/Domain/DonationRepositoryTest.php
* Addressed what I could from https://github.com/thebiggive/matchbot/pull/922 review
* Combined needlessly two step Salesforce field updates and simplified surrounding logic further
* Introduced a retry for saving the Salesforce fields and increased log severity level if it fails
* Moved some tests that asserted things about `push()` calls to the equivalent bus dispatches
=> MAT-363 – DB persist stability improvements; review fixes; test improvements

src/Migrations/Version20240807113023.php
Another charity should have this ref, but we have a duplicate constraint so that update from SF is getting blocked
=> Clear wrong HMRC ref no for one charity

src/Domain/DonationRepository.php
Per https://github.com/thebiggive/matchbot/pull/964#discussion_r1717119580
We have no info logs since this went live earlier this week, so the hypothesis about why it failed is probably right but we don't have much data yet. Will be good to have a prompt to investigate again if we get any occurrences with the new config.
=> MAT-363 – consider lost connections alarm-worthy, while keeping retry support for now

integrationTests/DonationPersistenceTest.php, integrationTests/DonationRepositoryTest.php, integrationTests/RedistributeMatchingCommandTest.php, src/Application/Actions/Hooks/StripePaymentsUpdate.php, src/Domain/Donation.php, src/Migrations/Version20240819164301.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Actions/Hooks/StripePaymentsUpdateTest.php, tests/Application/DonationTestDataTrait.php, tests/Domain/DonationTest.php
At present the calculation of the total paid by donor (core amount + any tip + any fee cover) is done several times and is expressed in four separate lines of code - one here and three in frontend. This PR makes matchbot record the result as it comes back from Stripe so that it can replace two of the lines in frontend. We may or may not also want to replace the final one, which is for displaying the expected amount *before* the payment is taken.
See https://github.com/thebiggive/donate-frontend/pull/1617#discussion_r1720106522
=> Don-993: Record total paid by donor on donation record

.circleci/config.yml
Seems we already set `CODECOV_TOKEN` at project level (c.f. [v4 upgrade notes](https://github.com/codecov/codecov-circleci-orb/releases/tag/v4.0.0)), so hopefully no documented BC breaks.
=> Try upgrading all orbs to latest

app/dependencies.php, integrationTests/ListRegularGivingMandatesTest.php, src/Domain/RegularGivingMandate.php, src/Domain/RegularGivingService.php, tests/Domain/RegularGivingMandateTest.php
Diff in test shows the change in output here:
```diff
"schedule": {
"type": "monthly",
"dayOfMonth": 12,
"activeFrom": null
+                   "expectedNextPaymentDate": "2024-09-12"
},
```
=> DON-1025: Expose mandate next payment date to frontend

integrationTests/ListRegularGivingMandatesTest.php, src/Domain/RegularGivingMandate.php, tests/Domain/RegularGivingMandateTest.php
Saying that we expect to take payment at 6am rather than midnight. Not expecting to display the time, only the date, but using 6am makes sure the date will be the same in at least the UTC and London timezones.
=> DON-1025: Avoid TZ discrepancies on mandate expectedNextPaymentDate

app/dependencies.php, src/Application/Actions/Donations/Confirm.php, src/Application/Commands/TakeRegularGivingDonations.php, src/Client/LiveStripeClient.php, src/Client/Stripe.php, src/Client/StubStripeClient.php, src/Domain/DomainException/NoDonorAccountException.php, src/Domain/DonationRepository.php, src/Domain/DonationService.php, src/Domain/DonorAccount.php, src/Domain/NoRegularGivingPaymentMethod.php, src/Domain/StripePaymentMethodId.php, src/Migrations/Version20240828120951.php, tests/Application/Actions/Donations/ConfirmTest.php, tests/Application/Actions/Donations/CreateTest.php, tests/Domain/DonationServiceTest.php
…unt table
I have tested this manually by editing data in my local database to have a donation in 'PreAuthorized' status with a `preAuthorizationDate` of yesterday, and making sure I have an entry for myself in the DonorAccount table with a working card's ID from stripe as my `regularGivingPaymentMethod`. Given that I can run in the docker container
```
./matchbot matchbot:take-regular-giving-donations
```
and my donation gets collected.
=> MAT-376: Take pre-authorized donation using payment method saved on donor account

matchbot-cli.php, src/Application/Commands/SetupTestMandate.php, src/Domain/Donation.php, src/Domain/DonorAccount.php, src/Domain/Money.php, src/Domain/RegularGivingMandate.php
Docblock from new command:
```php
/**
* Use to create a regular giving agreement for test purposes. Usage example:
*
* To create a regular giving mandate for the emergency campaign, with gift aid enabled, for
* a donor with the given identity server UUID, stripe customer ID and payment method ID, to donate £500 each month
* on the 20th day of the month, starting this month if today is <19th otherwise starting next month run:
*
* ./matchbot matchbot:setup-test-mandate --campaign Emergency --gift-aid
*      --donor-uuid 72f1e368-65f3-11ef-878f-fb0a039f0650 --donor-stripeid cus_xyxzaxasfdef
*       --donor-pmid pm_1xyzxzyxzyxzyxzyxzyxzyxz 500 20
*
* This doesn't create the intitial donation, but it does pre-authorise the 2nd and 3rd donations.
*/
```
=> MAT-376: Create command to generate a regular giving mandate for testing

integrationTests/ListRegularGivingMandatesTest.php, src/Application/Actions/Donations/Confirm.php, src/Application/Commands/SetupTestMandate.php, src/Application/Commands/TakeRegularGivingDonations.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Domain/DonorAccount.php, src/Domain/MandateService.php, src/Domain/RegularGivingMandate.php, src/Domain/RegularGivingMandateRepository.php, tests/Domain/MandateServiceTest.php, tests/Domain/RegularGivingMandateTest.php
Fixing issues to allow automatic repeat payment donations to be collected:
- Setting up stripe payment intent & reserving funds when creating donation
- Replacing public readonly properties on mandate with private readonly properties. Public readonly led to crashes due to https://github.com/doctrine/orm/issues/9432 . 
- DonationService no longer readonly to allow doubling it in tests.
=> Mat 376 cont iii

src/Migrations/Version20240304105340.php
See 934f886fa177c7f9 . Turns out I shouldn't have deleted the whole file, I should have just deleted or commented out the content of the migration. Doctrine Migrations tool doesn't like seeing migration files deleted.
=> Fix missing migration issue on staging

.psalm/psalm-baseline.xml, integrationTests/IntegrationTest.php, src/Application/Actions/Donations/Create.php, src/Application/HttpModels/DonationCreatedResponse.php, src/Client/LiveStripeClient.php, src/Client/Stripe.php, src/Client/StubStripeClient.php, src/Domain/Donation.php, src/Domain/DonationService.php, tests/Application/Actions/Donations/CreateTest.php, tests/Domain/DonationServiceTest.php
Passing the customer session client secret to frontend will allow the donor to view their saved cards and select one for use.
=> DON-896: Create stripe customer session with donation

src/Domain/DonationService.php
We saw an error on attempt to re-use a saved card:
Stripe\Exception\InvalidRequestException:
The `setup_future_usage` value on the ConfirmationToken you provided was null.  This is determined by the `setupFutureUsage` you provided when creating the `elements` object on your client. When the PaymentIntent/SetupIntent `setup_future_usage` value is set to on_session with a secret key, the only acceptable ConfirmationToken `setup_future_usage` values are on_session and off_session.
=> DON-896: Fix issue with attempting to re-save saved payment methods

.psalm/psalm-baseline.xml, integrationTests/DonationRepositoryTest.php, src/Domain/CampaignFunding.php, src/Domain/FundRepository.php, tests/Application/Actions/Donations/CreateTest.php, tests/Application/Commands/HandleOutOfSyncFundsTest.php, tests/Application/Commands/RedistributeMatchFundsTest.php, tests/Application/Commands/ResetMatchingTest.php, tests/Application/Matching/AdapterTest.php, tests/Domain/DonationRepositoryMatchFundsAllocationTest.php, tests/Domain/DonationTest.php, tests/Domain/FundRepositoryTest.php
This refactoring PR does technically add more lines than it removes, but the added lines are substantially simpler than the removed lines.
=> Fix 'PropertyNotSetInConstructor' issues in CampaignFunding class

app/dependencies.php, src/Application/Actions/Hooks/StripePaymentsUpdate.php, src/Application/Messenger/Middleware/AddOrLogMessageId.php, src/Application/Messenger/Stamp/MessageId.php, tests/Application/Messenger/Middleware/AddOrLogMessageIdTest.php
* [Delay handling of Stripe payment webhooks' queued messages](https://github.com/thebiggive/matchbot/commit/b15ba32c85a029b9a7a0aa1eda1722f2ed050d71); May reduce the risk of these important updates being superseded unhelpfully by overlapping ones
* Give all messages unique IDs
* Log those ID with all sends & receives
* Log donation UUID alongside where applicable
~~I've not tested the middleware yet, so draft for now.~~
=> MAT-377 – message push enhancements: improve traceability, reduce chance of unhelpful reverts

src/Application/Actions/Donations/Update.php
With our latest libs & constructor, this is now what happens if you leave out e.g. donation amount (missing constructor arg) or provide an invalid format email address (assertion valid).
We want an HTTP 400 and warning log for both of these, not 500 and error.
=> Also catch `MissingConstructorArgumentsException` and `AssertionFailedException` on Donation Update deserialise

src/Application/Commands/CancelStaleDonationFundTips.php, src/Domain/DonationService.php
`DonationService::cancel()` needs an open database transaction.
=> DON-1082 – fix stale tip cancellation

src/Application/Messenger/CharityUpdated.php, src/Application/Messenger/DonationUpserted.php, src/Application/Messenger/StripePayout.php
Should allow conditional parallel processing; most notably, not holding up quick donation upserts behind slow payout reconciliations
=> INFRA-138 – give SQS messages group IDs

src/Migrations/Version20241118151933.php
The charity's account wasn't set up fully at stripe to be able to recieve these donations, so they have no transaction ID so we can't send them to our SF instance.
=> Stop attempting to send donations to SF from today that can't be sent

src/Application/Actions/UpdatePaymentMethod.php
This can happen when a donor is updating their payment method at /my-account, as seen yesterday.
Not something matchbot can prevent, they would need to contact their bank.
We could improve the UX a bit by showing a friendly message but I don't think that's high priorty. This PR doesn't change the UX at all, only changes the log type from error to info
=> Don't alarm on stripe "Invalid account" error for updated payment method

tests/Domain/DonationRepositoryTest.php
Primarily, make `getRepo()` calls slightly less unwieldy by removing unused arg and naming others at call time
=> DonationRepositoryTest minor tidying

src/Domain/DonationRepository.php, tests/Domain/DonationRepositoryTest.php
Same goal as https://github.com/thebiggive/matchbot/pull/1105 but simpler and without introducing an extra lock.
Could do with testing, but probably better than the other option if I've not missed anything and it works.
=> MAT-393 – hold the existing funds release lock longer, to fix a race condition

src/Application/HttpModels/DonationCreate.php, src/Domain/Donation.php
Needed for Donation Funds "tips" to Big Give to have the correct info saved without an Update.
Targeting `develop` as I don't expect we would choose to merge this much before noon tomorrow anyway.
Feels like ideally we'd add tests too but I'm not sure what would be a valuable one as the gap we missed here sort of sits between apps. Maybe expanding the scope of (or adding) a regression test is the best option.
=> DON-1106 – map properties needed for Donation Create to save Gift Aid info

src/Domain/Money.php
This was randomly throwing an assertion exception in a test when given the input "258.40" because multiplying by 100 using floating point gives 25,839.9999999999963, not exactly 25,840.
This would have caused a real bug, more seriously if the assertion was not there, since `(int)(100 * "258.40")` returns 25839 not the 25840 you'd expect.
=> DON-1009: Fix error in \MatchBot\Domain\Money::fromNumericStringGBP

app/routes.php, src/Application/Actions/CollectRegularGivingForTest.php, src/Application/Commands/TakeRegularGivingDonations.php
To use, point your browser at URL such as
http://localhost:30030/v1/test-donation-collection-for-date/2020-03-01?secret=<secret>
and you should see something like:
```
Big Give Matchbot
============================================================================================
Actual current date: Thu, 09 Jan 2025 18:33:07
Running regular giving collection process with simulated timestamp Sun, 01 Mar 2020 00:00:00 
This endpoint is only available in test/dev environments, not in production.
--------------
matchbot:collect-regular-giving starting!
Simulating running on 2020-03-01 00:00:00
0 mandates may have donations to create at this time                           
0 donations are due to have Payment Intent set at this time                    
0 donations are due to be confirmed at this …
```
=> DON-998: Add action to allow testing collection of regular giving funds via http

.env.example, app/settings.php, integrationTests/IntegrationTest.php, phpunit.xml, src/Client/Campaign.php, src/Client/Common.php, src/Client/Donation.php, src/Client/Fund.php, src/Client/Mailer.php, src/Client/Mandate.php
I did think about whether to merge the Campaign, Donation, Fund and Mandate clients into one, which might also be a good simplification, and would make it easier to pass the shared base URI as a constructor param.
=> BG2-2797: Replace multiple SF API base URI env vars with single var

src/Application/Commands/TakeRegularGivingDonations.php, src/Domain/Campaign.php
Dealing with alarms seen on slack today. For regular giving campaign close should only stop *new* regular giving signups, not get in the way way of us collecting donations based on existing mandates. We only stop that when \MatchBot\Domain\Campaign::$regularGivingCollectionEnd is past.
=> Allow collecting regular giving donation after campaign close

src/Domain/Currency.php
See comments on ticket today. Stripe sends the iso code as lower case.
=> BG2-2774: Fix lower case currency code causing 500 error

src/Domain/CampaignRepository.php, src/Domain/Charity.php, src/Domain/DonationNotifier.php, src/Domain/PostalAddress.php, tests/Domain/CharityTest.php
I think I misinterpreted this in the doctrine docs:
>  In case all fields in the embeddable are nullable, you might want to initialize the embeddable,
>  to avoid getting a null value instead of the embedded object.
I thought they meant if not all fields were nullable it wouldn't be necassary to initialize the embeddable because the ORM would recognise when a non-nullable field was null in the DB and make the entire embeddable null.
But I don't think it is doing anything that clever, looks like it always constructs an instance of the embeddable when hydrating an object, so it can never be null on an entity that's been loaded from the DB. If there's a null in the DB for a non-nullable property then that property doesn't get initialized and the app crashes when it tries to read it.
Don't …
=> MAT-400: Fix ORM crash on null embeddable property

src/Application/Actions/Donations/ResendDonorThanksNotification.php, src/Application/Email/EmailMessage.php, src/Domain/DonationNotifier.php, tests/Application/Actions/Donations/ResendDonorThanksNotificationTest.php
To be used by us for support purposes if e.g. a donor makes a typo when entering their email address.
=> MAT-400: Allow resending donation email to alternate email address

src/Domain/CampaignRepository.php
The rawData isn't actually likely to be used for anything automated, but worth having for ad-hoc queries, and to give us the option to use for migrations.
=> MAT-400 (ish): Set rawdata on campaign when inserting for first time

src/Domain/Campaign.php, src/Domain/CampaignFunding.php, src/Domain/Charity.php, src/Domain/CommandLockKeys.php, src/Domain/Donation.php, src/Domain/DonorAccount.php, src/Domain/Fund.php, src/Domain/Money.php, src/Domain/RegularGivingMandate.php, src/Domain/SalesforceProxy.php, src/Domain/SalesforceReadProxy.php, src/Domain/SalesforceWriteProxy.php
The success message at https://app.circleci.com/pipelines/github/thebiggive/matchbot/5348/workflows/e5387e49-278f-4d79-80d4-dc0ac1ed054c/jobs/17001/parallel-runs/0/steps/0-110 shows that the deleted tokens here don't affect the mapping as used by the ORM. Removing the redundant tokens reduces the risk of the mapping info getting out of sync with the actual PHP types in future.
=> Refactor: Remove redundant doctrine mapping info, redusing risk of future bugs

src/Application/Messenger/Handler/MandateUpsertedHandler.php, src/Client/Common.php
Should make post-refresh sandboxes quiet, similarly to how we handle this for donations
=> Handle 404 campaign mandate pushes to SF only info log and stop future attempts

src/Client/Fund.php
Only INFO log because Staging data mismatches mean missing and mismatched funds are fairly normal
=> Reduce Staging fund push log noise

src/Domain/DoctrineDonationRepository.php, src/Domain/DonationService.php
* normal SF fields retry to INFO
* campaigns that aren't prewarmed, which may be non GMF, to WARNING
=> Reduce some log levels

src/Domain/CampaignRepository.php
Allow unusual data to be treated as a fully null address without a crash, for now.
=> Remove assertion about non-first charity address lines

src/Migrations/Version20250424095340.php
I've tested this by manually copying both the source row from the DonorAccount table and the to-be-corrected uuid from the donation table into my local machine database, and running the migration does update the donation as I expected
=> MAT-417: Correct details on one donation

src/Domain/DonationService.php
Seen occasionally during GMF25
=> Log more quietly after 3DS fails, then there's an unsuccessful extra Confirm action call

src/Migrations/Version20250506171748.php, src/Migrations/Version20250506174024.php
These migrations have not yet run in staging, because changing these columns with foreign key constraints is not allowed.
=> Disable foreign key checks as required during DB migrations.

phpstan-baseline.neon, src/Application/Commands/DeleteStalePaymentDetails.php, src/Client/LiveStripeClient.php, src/Client/Stripe.php, src/Client/StubStripeClient.php, src/Domain/StripePaymentMethodId.php, tests/Application/Commands/DeleteStalePaymentDetailsTest.php
…command
Once changes from
https://github.com/thebiggive/donate-frontend/pull/1968 are operating in each environment I'm planning to adjust this command so that it can also detatch all the payment methods we don't have a use for from donors who *do* have passwords set. Should only be needed for as long as takes to get through all the donor accounts / stripe customers from before the date of the front end change.
Dry run mode should help us see what it will do in advance, in dev env even if nowhere else.
=> MAT-390: Adjust matchbot:delete-stale-payment-details to also clear non-usable cards from passworded accounts

src/Application/Actions/GetPaymentMethods.php, src/Client/LiveStripeClient.php
Reverts thebiggive/matchbot#1351
I think losing the display of 'unspecified' methods is making regtests fail. Will look in more detail tomorrow.
=> Revert "MAT-390 part 3: Display all payment cards on payment methods page, us…"

.circleci/config.yml, integrationTests/CreateRegularGivingMandateTest.php, integrationTests/DonationMatchingTest.php, integrationTests/IntegrationTest.php, integrationTests/PullCharityUpdatedBasedOnSfHookTest.php, phpunit-integration.xml
We need to make sure that any db transactions opened during an integration test are committed or rolled back by the end so that it doesn't affect subsequent tests.
This change cuts about 40 seconds off the integration test runtime, which feels like a big saving to me given how often I'm pushing matchbot changes and waiting for a result.
=> MAT-421: Run integration tests without process isolation

src/Domain/DonationService.php, tests/Domain/DonationServiceTest.php
Also reduce donation enrol tries from 6 (which we didn't really decide on deliberately) to 2.
=> MAT-421 – simplify by removing old or over-complicated retry logic

schema/donation-summary-no-orm.sql, src/Migrations/Version20250520210732.php
THink we may have some config drift between different non-prod environments that meant this migration was able to run in one but not the other.
=> MAT-419: Remove new view that failed to deploy to one environment

app/routes.php, src/Application/Actions/Campaigns/Get.php
For the moment this just proxies to SF, but is added so that FE can start relying on it. Soon it will read the campaign from the matchbot DB and domain model.
=> MAT-411: Add get campaign route

src/Domain/Campaign.php, src/Domain/CampaignRenderCompatibilityChecker.php, src/Domain/CampaignService.php, src/Domain/Charity.php
In future we will probably want to generate an alarm and/or throw if this doesn't match. Right now we know it doesn't match so we just include the list of errors in the response, and FE can display it on the donation page (at least outside prod) until we've fixed them all.
To test make a donation on local to force matchbot to pull a campaign from SF, then view the API response at e.g.
http://localhost:30030/v1/campaigns/a05S900000IdO9lIAF
You should see quite a long list of errors something like this. (one of them is because I edited the campaign title in my my matchbot db)
My plan next is to make FE display these all near the top of the donate page.
=> MAT-411: Check campaign rendered from matchbot against what SF sent us.

composer.json, integrationTests/CampaignRepositoryTest.php, integrationTests/DonationRepositoryTest.php, integrationTests/PullCharityUpdatedBasedOnSfHookTest.php, schema/Campaign.sql, schema/MetaCampaign.sql, src/Domain/Campaign.php, src/Domain/CampaignRepository.php, src/Domain/CampaignService.php, src/Domain/MetaCampaign.php, src/Domain/SalesforceProxy.php, src/Migrations/Version20250605112912.php, src/Migrations/Version20250605113222.php, src/Migrations/Version20250605141453.php, tests/Application/DonationTestDataTrait.php, tests/Domain/CampaignTest.php, tests/TestCase.php
Kernel of this PR is change from
````
$parentRef = $sfCampaignData['parentRef'];
parentRef: $parentRef,
````
to 
````
parentRef: $campaign->getMetaCampaignSfId()?->value,
````
I think needed since MetaCampaignSfId is such a core concept, and the association between campaign and metacampaign will be needed to implement search that it should be fully represented in the matchbot model and not just use data direct from SF without interpreting it, and it needs to be indexed.
=> MAT-405: Link charity campaigns to associated metacampaigns

src/Domain/CampaignService.php
Reverts thebiggive/matchbot#1433
Reverted because we did get more distinct types of warnings in the last 24 hours, so we're maybe not quite ready to make this an alarm. Might try again tomorrow.
=> Revert "MAT-405: Start logging error instead of warning if campaign rendering…"

schema/MetaCampaign.sql, src/Domain/MetaCampaign.php, src/Migrations/Version20250709090013.php
We know 255 characters was insufficient. I suspect 500 would be OK for meta-campaigns but going with 1,000 for now to be reasonably safe.
Technically the Salesforce field supports 130,000 but it's also used by charity campaigns including imported ones, so I don't know if we can very quickly decide a sensible lower limit or enforce one at source for meta-campaigns. As far as I can see we don't have a dedicated equivalent to this field for charity campaigns, so can probably rely on JSON typed fields being much longer and assume we won't have an equivalent bug for those.
=> MAT-405 – fix Metacampaign summary length

src/Application/Actions/Campaigns/Get.php, src/Application/Actions/Campaigns/GetEarlyPreview.php, src/Application/Actions/Campaigns/Put.php, src/Application/Actions/Campaigns/UpsertMany.php, src/Client/Campaign.php, src/Domain/Campaign.php, src/Domain/MetaCampaign.php, tests/TestCase.php
Should be only in the list of ignored fields (where I think it needs to stay until SF switches over) after this
=> Phase out `x_` prefix for isMetaCampaign

src/Application/Commands/UpdateCampaignDonationStats.php
Afaik the stats are not yet really used for anything in production, and the error is very noisy, so replacing it with an info.
=> Replace stats error message with info

src/Domain/Currency.php
There are a few USD campaigns in our live SF, although none have been opened so far or are currently planned to be opened any time soon.
=> MAT-431: Allow campaigns to have USD currency instead of only GBP

app/routes.php, integrationTests/DonationPersistenceTest.php, schema/Donation.sql, src/Application/Actions/Donations/Confirm.php, src/Application/Actions/Donations/RemoveMatchingExpecation.php, src/Application/Commands/ExpireMatchFunds.php, src/Application/Matching/Allocator.php, src/Domain/Donation.php, src/Domain/DonationService.php, src/Migrations/Version20250806170146.php, src/Migrations/Version20250807132901.php, tests/Application/Actions/Donations/CancelAllTest.php, tests/Application/Actions/Donations/ConfirmTest.php, tests/Application/Actions/Donations/UpdateTest.php, tests/Application/Actions/Hooks/StripePaymentsUpdateTest.php, tests/Application/Matching/AllocatorTest.php
This will need a three step deploy to prod - first this PR, then something in Frontend to let matchbot know when a donor has accepted loss of their reserved match funds, and finally another change to matchbot to active the blocking of donations that don't have the expected match funds at the time of confirmation.
It works by adding a new field to donations that records the amount of match funds the donor expects to match. This is initially set to whatever match funds we allocate to the donation. If a donor gets an expiry alert and clicks OK then it will be set to zero. When the donor confirms their donation we will check that the match funds allocated are (at least) what they expect.
=> DON-1136:  Prevent donations from being confirmed without expected match funds

app/routes.php, src/Application/Actions/Sitemap.php, src/Domain/MetaCampaign.php, src/Domain/MetaCampaignRepository.php, tests/MatchBot/Application/Actions/SitemapTest.php, tests/TestCase.php
Before merging we may need to just hide any historic metacampaigns that we don't have accurate data or descriptions for in the DB.
=> DON-984: Include metacampaigns in sitemap

api.yaml, src/Domain/CampaignService.php
`parentUsesSharedFunds` is needed properly avoid showing a progress bar in that case. The parentRef is just added for possible future uses.
=> DON-1107: Add metacampaign info to shared funds

src/Domain/CampaignRepository.php
Only needs to be in prod long enough to run once, then can be reverted, although if left will just increase our running costs marginally.
=> BG2-2907: Update SCW 2025 campaigns from SF

src/Application/Actions/Campaigns/Search.php
To return an HTTP 400 and make logs less noisy
=> Catch invalid Search requests

src/Application/Commands/ExpirePendingMandates.php, src/Domain/RegularGivingService.php
Mostly just trying to make it clear to devs that there isn't an ID or something missing
=> Fix minor typo in automatic mandate cancellation reason

app/dependencies.php
Slack rate limits, and sending every single error individually, currently mean that code which would be fixing the data issue is never reached.
=> Turn off #regression-alarms temporarily to end vicious cycle

src/Application/Commands/TakeRegularGivingDonations.php
This error was recently triggered, but without knowing any identifiying details of the donation or its mandate its hard to see what to do about it.
=> Add more useful info to regular giving exception error log
